### ISSUE TITLE
Possible to add quilt and diff to the list?

### ISSUE THREAD

**Issue by i30817** [uutils/coreutils#1027]
I'm honestly shocked there isn't a portable implementation of quilt (which uses diff) to use on windows suggest windows people to use, so as you're already implementing a lot of the ecosystem i thought 'why not ask?'.

**Comment by Minoru** [comment]
Hi! I'm just a casual contributor, so don't take this comment for official position of the project.

Judging by #696, this repo is only concerned with re-implementing GNU coreutils. Since quilt isn't part of coreutils and [isn't even part of the GNU project](https://savannah.nongnu.org/projects/quilt), it most likely won't be re-implemented here.

However it looks like if you (or someone else) starts rewriting quilt, this repo's owners will be happy to reference your project to get it more visibility.

**Comment by Arcterus** [comment]
Yeah, @Minoru pretty much nailed it.  I'm open to potentially starting other projects under uutils (like maybe binutils, if someone wanted to do that), but I'd rather not pollute this project with random utilities.  I'm totally cool with helping other projects get more visibility as well.
