### ISSUE TITLE
make install with libstdbuf.so error

### ISSUE THREAD

**Issue by mssun** [uutils/coreutils#1072]
`$ make MULTICALL=y PREFIX=/tmp/src/coreutils/root install`
```
install /tmp/src/coreutils/target/release/libstdbuf.so /tmp/src/coreutils/root/lib/libstdbuf.so;
install: cannot stat '/tmp/src/coreutils/target/release/libstdbuf.so': No such file or directory
Makefile:300: recipe for target 'install' failed
make: *** [install] Error 1
```

What is `libstdbuf.so`? Is it still useful?

**Comment by Arcterus** [comment]
Sorry for the slow response.

Basically `stdbuf` cannot function without it, as the library gets injected into anything `stdbuf` calls to modify `stdin`, `stdout`, and/or `stderr`.

Because you pointed this out, I noticed the code to actually compile the library was deleted at some point, so I am adding it back in now.  Thanks :)

**Comment by Arcterus** [comment]
Let me know if something is still not working.
