### ISSUE TITLE
stat can't work in osx

### ISSUE THREAD

**Issue by framlog** [uutils/coreutils#1098]
Executing `uutils stat -f tmpfs` and it should crash then since there's no `/etc/mtab`.

**Comment by jamessan** [comment]
You're right that it shouldn't be parsing `/etc/mtab` directly.  This is even true on Linux, since that won't handle running inside a namespace.  For Linux, `/proc/mounts` should be used and specific solutions need to be added for other platforms.

However, your example is also flawed since the argument to `-f` isn't the _type_ of filesystem to report information about.  It should be a path, just like normal.  `-f` causes `stat` to show information about the filesystem on which the path resides instead of information about the file itself.

**Comment by bootandy** [comment]
original stat -f on mac does something different to linux:

> mac:
> -f format
>              Display information using the specified format.  See the FORMATS section for a
>              description of valid formats.
> linux:
> -f, --file-system
>               display file system status instead of file status
> 

so i think this is a case where we can't replicate behaviour on mac. 

Having said that I ran: **_uutils stat -f /_** and **_uutils stat -f /dev_**  on my mac and it provided me with block information that looked vaguely sensible.
