### ISSUE TITLE
Consider slimming down the make stuff

### ISSUE THREAD

**Issue by nox** [uutils/coreutils#1104]
Why does this project require `make` to build?

**Comment by Arcterus** [comment]
Most of the build/installation instructions are from before Cargo existed.  You can use Cargo to build the project (although `make` is still required due to the build process for `stdbuf`).  However, installing requires `make` because (as far as I know) Cargo does not support the creation of symlinks to another binary or the installation of man pages (which will eventually be written).

**Comment by nox** [comment]
> (although `make` is still required due to the build process for `stdbuf`).

There is nothing in that crate's makefile that couldn't be done directly in `build.rs` AFAIK.

Man pages does need something more than `cargo`, but the README should make it clear one can just invoke `cargo` to build.

**Comment by Arcterus** [comment]
Yeah, the README instructions do need to be updated.

I'm not really satisfied with `stdbuf`'s build process, so I'll see if there's a better way using `build.rs` later.

**Comment by Arcterus** [comment]
I've updated the `README` in #1105.

**Comment by nox** [comment]
> I'm not really satisfied with `stdbuf`'s build process, so I'll see if there's a better way using `build.rs` later.

Why is `libstdbuf` needed in the first place, can't we just setup the IO stuff from `stdbuf`'s `main` function?

**Comment by Arcterus** [comment]
`setvbuf()` doesn't affect programs started using `exec()` functions, so we need to use the `constructor` attribute and `LD_PRELOAD` to actually modify the buffering in the executed program.

**Comment by Arcterus** [comment]
`make` will no longer be required to build `stdbuf` once #1106 lands.
