### ISSUE TITLE
Start fuzz testing

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#1147]
We should start fuzzing to find security vulnerabilities at some point.  It may be easier to do this after #1124 is done.

**Comment by vitiral** [comment]
Personal recomendations:

- consider using https://github.com/AltSysrq/proptest
- consider creating a posix-specific fuzzing crate with proptest utility types, so that some generalization is possible across all the utilities. For example
  -  "table-like" text output with restricted values for rows, header, etc.
  - system-file specific fuzzer, i.e. generalize format of `/proc/*/*` items.
  - etc

**Comment by chadbrewbaker** [comment]
I'm working on getting the GNU Coreutils scripts to test the Rust binaries. Before fuzzing I would like to formalize the parsers to remove shotgun parse bugs that might be lurking.  Several fuzz rigs for coreutils binaries already exist: https://scholar.google.com/scholar?q=coreutils+fuzz&hl=en&as_sdt=0,16

I would also like to strace diff between GNU coreutils binaries and this project. Those differences need sifted through to eliminate security issues.

**Comment by chadbrewbaker** [comment]
This is choice. In addition to routine fuzzing, there are also scores of environment variables to fuzz if we support them all:  https://github.com/uutils/coreutils/issues/1582

**Comment by jaggededgedjustice** [comment]
Something that might be of interest is https://github.com/dyninst/fuzz  which was written for an academic paper (ftp://ftp.cs.wisc.edu/paradyn/technical_papers/fuzz2020.pdf). It found problems in fold (#1680 ), comm (I think just an inability to handle non valid utf-8 inputs) and ptx (I haven’t looked into that one yet).
Though it’s limited to checking for hangs/crashes and wouldn’t be a good fit for automated testing due to needing a lot of time to generate test cases up front.

**Comment by sylvestre** [comment]
>  wouldn’t be a good fit for automated testing due to needing a lot of time to generate test cases up front.

Sure but we could use https://github.com/google/oss-fuzz for on continuous testing.

**Comment by Funky185540** [comment]
I haven't dealt with testing much in my life, but I'm increasingly fascinated by fuzz testing and would love to have some "real" project (nothing academic) to pick up on it. I started reading the [Fuzzing Book](https://www.fuzzingbook.org/) a while ago in case that helps.

Should one try to integrate the rust coreutils in some of the existing fuzzing setups that @chadbrewbaker mentioned, or do something from scratch?

**Comment by sylvestre** [comment]
This book is indeed a great start.

See:
https://google.github.io/oss-fuzz/getting-started/new-project-guide/rust-lang/

Some examples of some rust crates:
https://github.com/google/oss-fuzz/blob/c25ca964c4363e6bcd5eab86c7d42d1a305d6a97/projects/flate2-rs/project.yaml
https://github.com/google/oss-fuzz/tree/30f3a8f1c0f5b072e77d5bea82709db04c53453d/projects/mp4parse-rust

And
https://github.com/google/oss-fuzz/pull/118

**Comment by sylvestre** [comment]
And the effort of @alastairreid at  Google Research:

 https://project-oak.github.io/rust-verification-tools/2021/07/14/coreutils.html

**Comment by Funky185540** [comment]
Impressive, a finished step-by-step tutorial... I'll look into that, thanks a lot!

**Comment by chadbrewbaker** [comment]
The blocking issue was a horribly broken ARM build chain that has been fixed in Ubuntu 22. I’ll try to build Alastair’s toolchain again this week.

**Comment by sylvestre** [comment]
On the same subject, this issue is very interesting too:
https://github.com/uutils/coreutils/issues/3785

**Comment by stappersg** [comment]
Current issue title is _"Start fuzz testing"_.  From #5343 do I understand that _fuzz testing_ has been started.

My actual question: _"Should this issue be closed?"_

**Comment by cakebaker** [comment]
Thanks for the hint, closing this ticket.

**Comment by sylvestre** [comment]
@stappersg you are everywhere ;)

**Comment by stappersg** [comment]
On Tue, Oct 10, 2023 at 04:21:53AM -0700, Sylvestre Ledru wrote:
> @stappersg you are everywhere ;)

  (-:     indeed,  I should focus more



Groeten
Geert Stappers
-- 
Silence is hard to parse
