### ISSUE TITLE
Inaccurate comments in numeric.rs of factor

### ISSUE THREAD

**Issue by shaobo-he** [uutils/coreutils#1198]
Hey guys,

These comments in numeric.rs of `factor` is inaccurate.

https://github.com/uutils/coreutils/blob/master/src/factor/numeric.rs#L27-L28

I think function `sm_mul` actually computes `(a*b)%m`. Also the precondition is not accurate. It's true that overflows occur when `m >= 2^63`. However, when `a` is greater than or equal `2^63`, `sm_mul` may not compute the correct result. For example,  `sm_mul(1<<63,2,3) == 0` while `(((1 as u128)<<63)*2)%3  == 1`.

**Comment by Arcterus** [comment]
I'm pretty sure both `sm_mul()` and `big_mul()` calculate `(a * b) % m`, so yeah.

I'll need to look at the code, but if `a` and `b` are never going to be that size, I don't think it's much of an issue.  `m` _can_ be that size though, which is why two separate functions are needed.  Did this cause an issue for you or something?

**Comment by shaobo-he** [comment]
@Arcterus Yes, `a` will never be that size. It didn't cause an issue for me. I'm just playing with it and found that this function may have some constrains on `a`.

**Comment by Arcterus** [comment]
If you have time you can submit a PR that fixes both of the issues and I'll merge it, but otherwise this will be pretty low priority.  Thanks for bringing this up though. :)
