### ISSUE TITLE
cat doesn't print files with "invalid unicode"

### ISSUE THREAD

**Issue by TheGoddessInari** [uutils/coreutils#1240]
At least on Windows, it prints
```
1  cat: text was not valid unicode
```
when attempting to cat -n or cat -b a file with presumably invalid unicode. Without any other arguments, it prints a blank line. This is an important distinction because GNU cat, and redirecting input (like cat < file) both work. Only when passing the file via arguments does it fail in this way.

Notably, this fails with most executables.

**Comment by Arcterus** [comment]
This main part of this issue  _seems_ to be caused by https://github.com/rust-lang/rust/issues/23344.  I'm not really sure if there's an easy fix unfortunately.  That said, I'm still not totally sure why the issue only shows up when opening a file directly.  I'm guessing it has to do with stdin only reading in UTF-16 pairs or something so there is no need to worry about half pairs.

The other part should be split into a separate issue (I'd appreciate it if you would do so).  We should not be separating the line number prefix write from the data write to avoid weird output like this.
