### ISSUE TITLE
Use coreutils as a library?

### ISSUE THREAD

**Issue by synek317** [uutils/coreutils#1253]
I've just found this crate, it looks amazing but there is one thing I cannot understand: why there are no pub functions to make it usable as a crate dependency? It could make rust a lot closer to become an alternative shell script language.

**Comment by Arcterus** [comment]
Currently the utilities themselves have not been designed to run that way.  To change them to support that use case will require a substantial effort due to a variety of issues (including the fact that many utilities manually exit in the case of an error rather than returning an exit status).  However, it is my plan to rewrite the utilities to support this at some point (although the main motivation is actually getting code coverage to work correctly; support for the library use case is more of a side effect).

A side note: I'm not sure Rust is a great language to function as an alternate shell script (scripting?) language due to the slow compile times (among other reasons).

**Comment by synek317** [comment]
Do you have any plan on how to do this iteratively? I think I could help, I would _love_ to write my scripts in rust instead of bash or python! 

I don't think compile times are big obstacle - last time I wrote really small python tool, I spend a couple of hours doing infinite number of fix - run - wait for an exception - fix - run - wait.... On the other hand, my rust app where I used ssh and zip crates for a very first time ran perfectly well as soon as it compiled. So summarized time (writing + compiling + debugging) is, imho, much better in rust.

**Comment by Arcterus** [comment]
The first step will likely involve restructuring the utilities to support the framework mentioned in #1124 (although at this point the design will likely be more similar to [this](https://github.com/mesalock-linux/mesabox/blob/1b32bde66a7bd6b6f2d3898cea6460ee01bfd2eb/src/lib.rs#L108)).  Following that we'll need to rewrite everything such that they always return `Result`s rather than just exiting the process on failure.  I'm not sure how we'd go about splitting this up into smaller steps unless we write a compatibility shim so `src/uutils/uutils.rs` and the file generated by `mkmain.rs` have a consistent entry point for each utility.

I guess it depends on what kind of tool you're writing.  If it's large or complex enough Rust could be a good choice.

**Comment by vks** [comment]
Why would you want to use the the crates here instead of directly using the Rust libraries that uutils employs?

**Comment by Arcterus** [comment]
Do you mean why would you want to embed something like `cksum` or `cut` in your program?  Well, first off, if you're writing a shell, you can use them as builtins rather than needing to either `fork+exec` and executing an external command or implementing them yourself.  Another example would be to have common cross-platform commands for _e.g._ a build system.  Basically, if you were to directly use the Rust libraries that `uutils` uses, you'd be duplicating effort.  You would also need to manually handle the platform differences we try to smooth out.

**Comment by sylvestre** [comment]
I think it is a wontfix
