### ISSUE TITLE
Implement ls

### ISSUE THREAD

**Issue by LeoTestard** [uutils/coreutils#126]
I'd like to work on this. (I already started in fact).
I saw there was already #34 but no answer since 3 months so I'd like to take the liberty to do it if there is no problem with that.

**Comment by peschkaj** [comment]
I noticed that no work has progressed on this issue since July of 2014.

I've created a barebones implementation of `ls` at https://github.com/peschkaj/coreutils/commit/9716862cfe61bb35615ffe6d08c3d044369aff59

This builds and produces very limited output on Windows with Rust 1.7.0 - current output is roughly equivalent to `ls -l` or `ls -lh`. There's plenty of outstanding work and the lack of tests currently has me reluctant to send a PR.

Outstanding tasks:

- [ ] Integration tests
- [ ] Basic `ls` output
- [ ] Support for additional `ls` options
- [ ] Retrieving owner and group information on Linux
- [ ] Processing & formatting permissions on Linux
- [ ] Correct error codes depending on where `ls` fails.

**Comment by wy193777** [comment]
How could I get file MetadataExt for Windows? I couldn't get functions under MetadataExt on Windows.

**Comment by peschkaj** [comment]
The best bet for getting file metadata on Windows would be asking @retep998 - he maintains https://github.com/retep998/winapi-rs/. If nothing else, he can point you in the right direction.

**Comment by wy193777** [comment]
Thanks, I've found what I want. Because I just have one Windows PC, I will just write it for windows.

**Comment by retep998** [comment]
The documentation for `std::os::windows::fs::MetadataExt` is only included with the Windows distributions of Rust, so you can't use the online documentation for that. If `MetadataExt` doesn't provide all the information you want you can call [`GetFileInformationByHandleEx`](https://retep998.github.io/doc/kernel32/fn.GetFileInformationByHandleEx.html) ([MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364953%28v=vs.85%29.aspx)) on the handle to get all sorts of information.

**Comment by wy193777** [comment]
Today I spend lots of time trying to call `GetFileInformationByHandleEx` and get file info. Before I call `GetFileInformationByHandleEx`, I first need to call [`CreateFileA`](https://retep998.github.io/doc/kernel32/fn.CreateFileA.html) But this function couldn't get a file handle if the file has been opened. What should `ls` do if a user wants opened file's i-node number on Windows?

**Comment by retep998** [comment]
If you have an `std::fs::File` then you can use `std::os::windows::io::AsRawHandle::as_raw_handle` to get a handle from the file, and then you can pass that to functions like `GetFileInformationByHandleEx`. Also you really don't want `CreateFileA` as that is not unicode friendly whatsoever.

**Comment by wy193777** [comment]
What's the Windows equivalent for Unix/Linux file Owner and Group name?

**Comment by retep998** [comment]
There is a direct Windows equivalent for file owner. There is no equivalent group owner. There is most definitely no chmod equivalent. There is a delightfully complicated access control list system but that's sufficiently overwhelming that an entire library would need to be dedicated to that.

**Comment by WildYorkies** [comment]
https://github.com/ogham/exa

Sharing here for posterity @ogham
