### ISSUE TITLE
MINOR: Suffix for distro that uses uutils?

### ISSUE THREAD

**Issue by Kreyren** [uutils/coreutils#1347]
What suffix should be used for a distro that uses uutils instead of coreutils?

alike `DistroName RNU/Redox` ?

**Comment by ids1024** [comment]
It's not entirely an equal comparison, since the "GNU" in "GNU/Linux" refers to more than just coreutils, such `glibc`, `gcc`, and various utilities that are distributed separately from GNU `coreutils` (`sed`, `grep`, `awk`, `make`, etc).

That said, at least if a substantial percentage of those other utilities ended up being developed under the uutils umbrella (like [findutils](https://github.com/uutils/findutils)), the term might not be inappropriate.

**Comment by Kreyren** [comment]
Noted, ty for info
