### ISSUE TITLE
Document what remains to do in "Partially done" commands

### ISSUE THREAD

**Issue by pfmoore** [uutils/coreutils#1437]
There appears to be a lot of variation in how complete the "partially done" commands are. For example `od` seems fairly complete, but `date` doesn't even support simple usages like `date +%Y%m%d`, and `sort` seems to have a good selection of options, but is missing some relatively important ones like sort keys.

It would be really useful if there were some documentation clarifying how complete the partially done commands are, to help people understand what's available (I am looking for Windows equivalents of Unix commands, and would, for example, use this project for many of them, but would probably not install `date` as it stands, or only make it available via the `uutils` command).

**Comment by Arcterus** [comment]
This is something I have been meaning to do.  I'll see if I can get this done in the next few weeks or so.

**Comment by sylvestre** [comment]
Too quick, I am not sure :) Reopen is cheap!

**Comment by tertsdiepraam** [comment]
I think we can close this. Not because it's been fixed necessarily, but because we document missing features in other ways.

Let me start of by saying that I've always found the "partially done" divide a bit arbitrary. It's not been kept up to date at all, I believe. The list has been composed fairly arbitrarily over the years and the reasoning has not been recorded as far as I know. That is why I've removed the list in https://github.com/uutils/coreutils/pull/4511.

However, it is important to keep track of what remains to be done! So that's why we keep those things in issues. For example, say you want to know what remains to be done for `ls`. You could look at:

 - the `ls` tracking issue: https://github.com/uutils/coreutils/issues/1872
 - issues with the `U - ls` label: https://github.com/uutils/coreutils/labels/U%20-%20ls
 - GNU test coverage: https://uutils.github.io/user/test_coverage.html
 - TODO's in the source code.
