### ISSUE TITLE
rm: -v -r should match GNU's output

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1768]
with rm from GNU:
```
$ mkdir a
$ rm -rf -v a
removed directory 'a'
```
With the Rust implementation:
```
$ mkdir a
$ rm -rf -v a
removed 'a'
```

**Comment by goodbadwolf** [comment]
I would like to take this up if no one else is

**Comment by billyb2** [comment]
@jhscheer Yeah that tripped me up too when I was writing my pull, I want to look for where remove_dir is called in the program but unfortunately my editor isn't all that great

**Comment by jhscheer** [comment]
I looked at it some more.

If `rm -rf` is called on a directory, we get `handle_dir` -> `remove_dir_all`
If `rm -rfi` is called on a directory, we get `handle_dir` -> `remove_dir`

However, the comment L249-250, indicates that `remove_dir_all`  is only used for windows compatibility. 
```
// we need the extra crate because apparently fs::remove_dir_all() does not function
// correctly on Windows
```

1. I think the `stdout` for `-v` should be fixed in `remove_dir`.
2. To me it looks like not calling `remove_dir` with flag `-f` is a bug.
3. To keep the `stdout` between windows systems identical to non windows system, there should probably be a `cfg(windows)` in `remove_dir` and the `remove_dir_all` should be moved from `handle_dir` to `remove_dir`.

@maintainers, is this the way to go?

**Comment by jhscheer** [comment]
This was fixed in #1839 and can be closed.

**Comment by JnRouvignac** [comment]
Another one that can be closed apparently :)

**Comment by sylvestre** [comment]
thanks
please contact me sylvestre@debian.org if you are looking for good first bug!
