### ISSUE TITLE
implement dd

### ISSUE THREAD

**Issue by backwaterred** [uutils/coreutils#1861]
I'd like to work on implementing dd. I see this has been attempted before. Any idea what the stumbling blocks were?

WIP is [here](https://github.com/backwaterred/coreutils)

**Comment by sylvestre** [comment]
Great news. See
https://github.com/uutils/coreutils/pull/1126

**Comment by Arcterus** [comment]
The biggest issue is that you have to manually parse the command-line arguments rather than simply using `clap`, `getopts`, etc.  You should also implement progress status, which requires more bookkeeping.  The actual copying is pretty simple, although there are quite a few different block size parameters and handling all of them can be somewhat bothersome.

Another thing you should be aware of is `conv`.  You'll need to be able to convert from ASCII to EBCDIC and vice versa (among other conversions).  This specific set of conversions is almost pointless in 2021, but you need to do it (and you'll need to add tests).

If `conv` is present, you'll need to shove a conversion function between the reads and the writes.  However, if it's not present and the other arguments don't prevent you from doing so, you should try to use `splice()` on Linux/Android for fast copies.  On more recent versions of Rust, `io::copy()` already does this internally, but since you'll have all the bookkeeping for keeping track of progress, it might be easier to manually use `splice()` from `nix`.

Depending on the platform, `SIGUSR1` and `SIGINFO` should cause `dd` to print its current status.

This is all I can think of at the moment, but there might be more.  I'll post another comment if I think of anything else.

**Comment by Mythbusters123** [comment]
I see that this has been inactive. I will try to take this up.

**Comment by backwaterred** [comment]
@Mythbusters123 Funny that you should message today. I am doing some final testing and catching up my fork with the main branch. This definitely took me longer than I expected, but I should have a PR by the end of this week.

**Comment by Mythbusters123** [comment]
Oh. I would happy to look it over for you! This was meant for me to learn rust, but I guess I will try and implement one that still isn't done. Thank you for doing this (I guess lmao)

**Comment by backwaterred** [comment]
Thanks @Mythbusters123. I would be happy for an extra set of eyes on the code! I am also working on this to get better at Rust.

**Comment by Mythbusters123** [comment]
Do you have a discord account or an email that I could contact you easier through there? Thank you @backwaterred

**Comment by backwaterred** [comment]
Sure @Mythbusters123. q8ejmhxlc@relay.firefox.com is forwarded to my regular email.

**Comment by backwaterred** [comment]
By way of update: My focus this week has been on testing using the uutils macros (rather than the unit tests I was using for dev) and bringing my fork in line with the uutils mainline so that I can open up development to the community. Unfortunately, this week has been a bit busy for me, and I've also run into a few snags. I am hopeful that next week will see more progress, including that PR I promised.

**Comment by tertsdiepraam** [comment]
Implemented in #2474
