### ISSUE TITLE
CI/CD fails with message about Cargo.lock

### ISSUE THREAD

**Issue by kevinburkemeter** [uutils/coreutils#1892]
I submitted a PR with no changes to Cargo.lock but got the following error in response: 

```
  # Confirm compatible 'Cargo.lock'
  # * 'Cargo.lock' is required to be in a format that `cargo` of MinSRV can interpret (eg, v1-format for MinSRV < v1.38)
  cargo fetch --locked --quiet || { echo "::error file=Cargo.lock::Incompatible 'Cargo.lock' format; try \`cargo +1.33.0 update\`" ; exit 1 ; }
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    PROJECT_NAME: coreutils
    PROJECT_DESC: Core universal (cross-platform) utilities
    PROJECT_AUTH: uutils
    RUST_MIN_SRV: 1.33.0
    RUST_COV_SRV: 2020-08-01
Error: Incompatible 'Cargo.lock' format; try `cargo +1.33.0 update`
Error: Process completed with exit code 1.
```

I can update Cargo.lock by running `cargo update`, but I'm not super familiar with Rust and don't know what the file should look like.

https://github.com/uutils/coreutils/pull/1890/checks?check_run_id=2177568946

**Comment by Arcterus** [comment]
Looks like it somehow got updated using a newer version of Rust.  You can wipe the file locally and then run `cargo +1.33 update` (after installing Rust 1.33 via `rustup`).  If everything seems to work fine locally, you can just add the new `Cargo.lock` to your PR and the CI should work (you should use `cargo +1.33` instead of just plain `cargo` when testing locally to ensure the file doesn't get screwed up again).

**Comment by sylvestre** [comment]
I already fixed it here:
https://github.com/uutils/coreutils/pull/1896
