### ISSUE TITLE
GNU tests: factor is breaking the build

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1941]
```
PASS: tests/factor/t20.sh
gawk: cmd. line:1: (FILENAME=- FNR=173) fatal: node.c:415:make_str_node: r->stptr: can't allocate -2147483645 bytes of memory (Cannot allocate memory)
```

https://github.com/uutils/coreutils/pull/1922/checks?check_run_id=2206694573

This makes the GNU test fails.
We should either fix factor or disable this test

cc @nbraud @jaggededgedjustice

**Comment by jaggededgedjustice** [comment]
it's not factor, it's #1879. This error happens when make is generating the summary log as gawk fails to handle the ~2GB line, so all the test run and you can download the log archive and look through them. I wasn't sure how to fix this issue because I'm still new to rust. To stop the problematic test being run the line
```
returns_ 1 $prog '%.*dx\n' $INT_OFLOW 0 >>out 2> /dev/null || fail=1
```
needs to be removed from `tests/misc/printf.sh`

**Comment by sylvestre** [comment]
@jaggededgedjustice is that something you could do? thanks :)
