### ISSUE TITLE
more: pipe isn't working

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1971]
Not sure it is used but:
```
$ cat foo.txt|more
```
is working with GNU.

Fails with our version:
```
$ cat foo.txt|./target/debug/coreutils more
more: incorrect usage
```

https://github.com/uutils/coreutils/blob/master/src/uu/more/src/more.rs
A test should be added in
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_more.rs

**Comment by sylvestre** [comment]
Probably, do you have one in mind?

**Comment by Wabuo** [comment]
I'm keen giving it a shot(first proper rust project).
>there are now decent cross-platform terminal crates

I guess that should be an uutils wide decision, how do we go about this? Shall I open an Issue?
What are the requirements we have? Things like:
- Supported platforms(Linux, Windows, BSD's, RedoxOS ..) architectures (i686, x86_64, RISC-V ..) [shouldn't that be a problem of the OS?]
- What dependencies will it pull in?
- code quality
- what happens if it gets abandoned, how easy can we move on or take it over?
- ...

Do we want more and less? Shall they use the same code base?

What did I miss?
Who got some input?

Cheers Wabuo

**Comment by tertsdiepraam** [comment]
Hi @Wabuo! Note that there is an open PR for a `more` rewrite which uses `crossterm`: https://github.com/uutils/coreutils/pull/2109. If you want to work on `more` you might want to wait for that to get merged and work from there.

**Comment by Wabuo** [comment]
Oh well looks like I suck at using the search function, sorry.

Of I go, looking for another low-hanging fruit ...

**Comment by tertsdiepraam** [comment]
Fixed as a part of https://github.com/uutils/coreutils/pull/2109
