### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by Mikadore** [uutils/coreutils#1982]
We want the `CmdResult` struct to hold `Vec<u8>`s instead of `String`s so that we can run tests with non-utf8 output,
#1977 Defined a public API, but unfortunately, many tests still access fields of `CmdResult` directly.

E.g. 
```rust
fn test_multiple_formats() {
    let input = "abcdefghijklmnopqrstuvwxyz\n";
    let result = new_ucmd!()
        .arg("-c")
        .arg("-b")
        .run_piped_stdin(input.as_bytes());

    assert_empty_stderr!(result);
    assert!(result.success);
    assert_eq!(
        result.stdout,
        unindent(
            "
            0000000   a   b   c   d   e   f   g   h   i   j   k   l   m   n   o   p
                    141 142 143 144 145 146 147 150 151 152 153 154 155 156 157 160
            0000020   q   r   s   t   u   v   w   x   y   z  \\n
                    161 162 163 164 165 166 167 170 171 172 012
            0000033
            "
        )
    );
}
```
Is to be re-written as
```rust
fn test_multiple_formats() {
    let input = "abcdefghijklmnopqrstuvwxyz\n";
    new_ucmd!()
        .arg("-c")
        .arg("-b")
        .run_piped_stdin(input.as_bytes())
        .success()
        .no_stderr()
        .stdout_is(unindent(
            "
            0000000   a   b   c   d   e   f   g   h   i   j   k   l   m   n   o   p
                    141 142 143 144 145 146 147 150 151 152 153 154 155 156 157 160
            0000020   q   r   s   t   u   v   w   x   y   z  \\n
                    161 162 163 164 165 166 167 170 171 172 012
            0000033
            "
        ));
}
```
I'll start work on `od` & `ls` for now. If you're interested in doing some, please comment so we don't do the same work twice!
It's not very hard; some tips:
- use the find/replace functionality of your IDE (or `sed` even)
- take a look at `tests/common/util.rs` to see all the functions a `CmdResult` has
- you can locally make these fields private (but please don't commit this!) and fix the resulting errors 
Lastly, please make sure you're not changing the tests' functionality.

**Comment by tertsdiepraam** [comment]
I love this API! In the `ls` tests, I often found myself manually printing the `stdout` and `stderr` before doing any assertions, which was a little bit cumbersome. Specifically, I couldn't use `succeeds` directly because that wouldn't give me the actual error if it failed. I thought of some ways to fix this, which I could implement myself, but I'd like to hear which option (if any) you would prefer.
- making the `run` method print automatically
- making `succeeds` & `succeed` and `fails` & `fail` print `stdout` and `stdout` if the program does not behave as expected
- adding a method that prints `stderr` and `stdout`

**Comment by sylvestre** [comment]
Just like @tertsdiepraam just said :)

**Comment by Mikadore** [comment]
Personally, the second option seems the most sensible. But I think we should also provide some explicit methods for this. (e.g. `print_stderr`)

**Comment by jhscheer** [comment]
I'm in the process of refactoring some tests in order to no longer use the fields of `CmdResult` directly.
Sometimes it's useful to have a handle on both `stdout_str` and `stderr_str`, however as far as I understand that's not possible right now.

I was thinking about something like a collection instead of a method for each individual value.
Like maybe a method returning a struct containing all the moved values, i.e. stdout_move_{str, bytes} and stderr_move_{str, bytes}.

What do you think?

**Comment by Mikadore** [comment]
> I'm in the process of refactoring some tests in order to no longer use the fields of `CmdResult` directly.
> Sometimes it's useful to have a handle on both `stdout_str` and `stderr_str`, however as far as I understand that's not possible right now.
> 
> I was thinking about something like a collection instead of a method for each individual value.
> Like maybe a method returning a struct containing all the moved values, i.e. stdout_move_{str, bytes} and stderr_move_{str, bytes}.
> 
> What do you think?

I mean, you can always just have 
```rust
let result = ...;
result.stderr_str();
result.stdout_str();
```
It is true that there is no way to move both `stderr` and `stdout`, so maybe adding methods
which return `(String,String)` & `(Vec<u8>, Vec<u8>)` is a good idea. 

> Like maybe a method returning a struct containing all the moved values, i.e. stdout_move_{str, bytes} and stderr_move_{str, bytes}.

IDK whether it makes sense to introduce new types here, IDRC tbh though

**Comment by jhscheer** [comment]
@Mikadore Yes, sorry. A moment after I commented it occurred to me that I was mistaken.

**Comment by tertsdiepraam** [comment]
@Mikadore you mentioned that you were working on refactoring the `ls` for this. Are you still working on that or can I give it a go?

**Comment by Mikadore** [comment]
> @Mikadore you mentioned that you were working on refactoring the `ls` for this. Are you still working on that or can I give it a go?

haven't came around to it yet, so sure, go for it!
