### ISSUE TITLE
uname processor and hwplatform

### ISSUE THREAD

**Issue by dm9pZCAq** [uutils/coreutils#2041]
for me `GNU uname` return correct `processor` and `hwplatform` in 3 of 5 `x86_64` machines

https://github.com/uutils/coreutils/blob/20d071a482a568f13b4f5862d57c06f815ceb5d5/src/uu/uname/src/uname.rs#L139-L150

also here is code from `GNU uname`, it's actually do something to determine this info and not just print `"unknown"`:
* [processor](https://github.com/coreutils/coreutils/blob/v8.32/src/uname.c#L301-L343)
* [hwplatform](https://github.com/coreutils/coreutils/blob/v8.32/src/uname.c#L345-L368)

**Comment by LevitatingBusinessMan** [comment]
We'd have to think about how we should retrieve this information per platform.
For Linux systems we can use `sysinfo` from libc.
MacOS has a library `sysctl`.
I am not sure what to use on windows.

**Comment by dm9pZCAq** [comment]
> I am not sure what to use on windows.

maybe [this](https://docs.microsoft.com/en-us/windows/win32/sysinfo/getting-hardware-information) can help

**Comment by tertsdiepraam** [comment]
Still an issue. It'd be cool if we could do better than GNU in this area. Maybe to unblock this a bit, we could implement this for Linux first and think about other platforms later?

**Comment by LevitatingBusinessMan** [comment]
@tertsdiepraam I'd care to work on this. Gotta have to find some free time first though. Maybe sometime later in this month.

**Comment by dm9pZCAq** [comment]
in linux you can get it from parsing `/proc/cpuinfo`

[here](https://notabug.org/dm9pZCAq/dm9pZCAq-coreutils/src/master/src/uname/cpuinfo.c) is how i do this

**Comment by LevitatingBusinessMan** [comment]
This might be a bit harder than I thought. So I wasn't able to find any x86_64 machine of my own that had results for "processor" or "hwplatform". I had a few friends test their results for me, but it doesn't help that MacOS uses a different `uname`.

`n/a` means the version of uname used didn't support that flag.

My ryzen 3
```
machine: x86_64
processor: unknown
hwplatform: unknown
```

M1 Macbook
```
machine: arm64
processor: arm
hwplatform: n/a
```

Android
```
machine: aarch64
processor: unknown
hwplatform: unknown
```

A different Android
```
machine: armv8l
processor: n/a
hwplatform: n/a
```

Intel Macbook I think
```
machine: x86_64
processor: i386
hwplatform: n/a
```

So first we have to figure out what we want these flags to even do exactly.

## What does GNU do?
### processor (-p)
Before [this](https://github.com/coreutils/coreutils/commit/510f7bfe8790b75cc84742626e4a171e3727bf1f) commit GNU relied on a `sysinfo` found in `<sys/systeminfo.h>` (if it existed). I couldn't find much out about this, I am assuming it's extremely deprecated? GNU uses it to fetch the `SI_ARCHITECTURE` variable.

Then it tries using `sysctl`, which has been deprecated since Linux 2.6.24 and was removed in Linux 5.5. GNU tries to fetch `UNAME_PROCESSOR` here.

So no wonder that it doesn't work on anything I tested it on.

Man pages tell us to use `/proc/sys` instead.

### hardware (-p)
Exact same stuff. But it fetches `SI_PLATFORM` or `UNAME_HARDWARE_PLATFORM`.

So we're sailing uncharted waters here. Cool.

I think we should maybe consider dropping these flags. They I don't think they currently do anything in `uname`, and I don't see their significance either. And all of the other settings just pull info from `<sys/utsname.h>`.
