### ISSUE TITLE
touch -m does not follow GNU touch

### ISSUE THREAD

**Issue by rethab** [uutils/coreutils#2055]
Might there be an issue with daylight savings time in touch?

The output from GNU touch and uutils touch seems to differ if I take a date in May:
```bash
> touch -m -t 201505150000 gnu
> cargo run --features "feat_os_unix" -- touch  -m -t 201505150000 uutils
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/coreutils touch -m -t 201505150000 uutils`
> ls -lh --full-time gnu uutils 
-rw-rw-r-- 1 rethab rethab 0 2015-05-15 00:00:00.000000000 +0200 gnu
-rw-rw-r-- 1 rethab rethab 0 2015-05-15 01:00:00.000000000 +0200 uutils
```
However, repeating the same for a date in January:
```bash
> rm gnu uutils
> touch -m -t 201501010000 gnu
> cargo run --features "feat_os_unix" -- touch  -m -t 201501010000 uutils
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/coreutils touch -m -t 201501010000 uutils`
> ls -lh --full-time gnu uutils 
-rw-rw-r-- 1 rethab rethab 0 2015-01-01 00:00:00.000000000 +0100 gnu
-rw-rw-r-- 1 rethab rethab 0 2015-01-01 00:00:00.000000000 +0100 uutils
```

I discovered this, because I on my machine, the test `test_du_time` fails (cleaned output for clarity):
```bash
> cargo test --features "feat_os_unix" -- test_du_time
[..]
test test_du::test_du_time ... FAILED

failures:

---- test_du::test_du_time stdout ----
current_directory_resolved: 
run: /home/rethab/dev/coreutils/target/debug/coreutils touch -a -m -t 201505150000 date_test
run: /home/rethab/dev/coreutils/target/debug/coreutils du --time date_test
run: rm date_test
thread 'test_du::test_du_time' panicked at 'assertion failed: `(left == right)`
  left: `"0\t2015-05-15 01:00\tdate_test\n"`,
 right: `"0\t2015-05-15 00:00\tdate_test\n"`', /home/rethab/dev/coreutils/tests/by-util/test_du.rs:191:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ajanicij** [comment]
I am working on this.

**Comment by ajanicij** [comment]
This is definitely a DST issue.

For example, here's how GNU coreutils touch behaves for times on March 14 2021 in my area (Toronto, UTC-4). That was the date when the clock changed to daylight saving time at 2 AM, so it jumped to 2 AM to 3 PM.

1. Set modification time to 1:59:
$ touch -m -t 202103140159 uutils
$ ls -lh --full-time uutils
-rw-rw-r-- 1 sasha sasha 0 2021-03-14 01:59:00.000000000 -0500 uutils

2. Set modification time to 2:00 - touch does not allow it:
$ touch -m -t 202103140200 uutils
touch: invalid date format ‘202103140200’

3. Set modification time to 3:00:
$ touch -m -t 202103140300 uutils
$ ls -lh --full-time uutils
-rw-rw-r-- 1 sasha sasha 0 2021-03-14 03:00:00.000000000 -0400 uutils

Rust version works correctly for case 1. For 2, it succeeds (instead of failing) and sets the time to 3:00. For 3, it succeeds and sets the time 4:00 (instead of 3:00).

I am still trying to figure out how to deal with this issue.
