### ISSUE TITLE
ls -R could run in parallel to improve the performances (aka ls -R is much slower than GNU's)

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2069]
Running ls -R on a big tree (firefox sources for example), we are 5 times slower than the GNU version.
```
$ hyperfine --warmup 2   --show-output 'ls -al -R mozilla-central.hg  > /dev/null' '/home/sylvestre/dev/debian/coreutils//target/release/coreutils ls -al -R mozilla-central.hg > /dev/null'  
...
Summary
  'ls -al -R /home/sylvestre/dev/mozilla/mozilla-central.hg  > /dev/null' ran
    4.71 ± 0.31 times faster than '/home/sylvestre/dev/debian/coreutils//target/release/coreutils ls -al -R mozilla-central.hg > /dev/null'
```
Running it in parallel could help.

**Comment by siebenHeaven** [comment]
Hello,

I'm looking into contributing to rust project as the next step for my "Learning Rust" journey. 

This seems like a good issue to take up - I have some experience with parallelizing with rayon - is that something we want to explore here?

I am also curious - would looking for other performance bottlenecks before parallelizing would be worthwhile?

**Comment by ArniDagur** [comment]
@siebenHeaven Great. I would also look at https://github.com/uutils/coreutils/pull/1379; `du` is a tool which benefits from parallel directory walking in a similar manner. The first thing I'd do before rolling our own directory walker is looking at [`ignore`](https://crates.io/crates/ignore). That's the super fast parallel directory walker that `ripgrep` and `fd` use.

**Comment by tertsdiepraam** [comment]
Hi @siebenHeaven! Awesome that you want to pick this up! I think you are right that there are a lot of parts of `ls` that could be improved without parallelization. For example, the metadata for each file gets retrieved separately for each part of the program that uses it (this is probably where those syscalls come from). It could indeed be a relatively easy performance win to store the metadata along with the paths to reuse it. String handling is also a little bit clunky in certain places, because there are a lot of calls to `OsString::to_string_lossy()` (often multiple times per file) and some unnecessary allocations.

**Comment by siebenHeaven** [comment]
Yes, 
I've been trying to cache the metadata so that the calls to statx syscalls will be saved + trying to reduce unnecessary clones along the way in hot paths - will get back on some results with that soon.
