### ISSUE TITLE
Is there a policy on Apache 2-only dependencies?

### ISSUE THREAD

**Issue by electricboogie** [uutils/coreutils#2086]
I have a crate I may want to use but it is Apache 2.0 licensed only.  Thanks!

**Comment by dhodder** [comment]
Hi @electricboogie, if you still wish to add an Apache License 2.0 dependency, I'd suggest adding an issue (or maybe even a PR) noting the dependency, why you're adding it and for which utilities it's for. If folks aren't happy about the license they might be able to suggest an alternative dependency. Thanks. :)

**Comment by dhodder** [comment]
Issue #1994 adds a statement on licensing to `CONTRIBUTING.md`. It confirms some licenses we consider acceptable for dependencies (e.g. the Apache-2.0/MIT dual-license) and some licenses that we do not consider acceptable (e.g. the GNU GPL). However, I deliberately avoided mentioning the Apache 2.0 license alone, because the consensus amongst uutils developers didn't seem as clear to me.

In [pull request 2493](https://github.com/uutils/coreutils/pull/2493), @tertsdiepraam suggested:
> ... The main difference with MIT seems to be that you have to state the changes you make, so I'm leaning towards allowing it for dependencies, but not allowing copying code from Apache 2.0 projects. This ensures that we don't modify the code without stating the changes. Does that make sense?

I suggested that we could add a third license category, between "acceptable" and "licenses we will not use":

>Licenses accepted in referenced dependencies, on a case-by-case basis, when there is no MIT-licensed alternative:
>
>* Apache License, version 2.0

It was suggested we check what @sylvestre and @rivy think.

Alternatively we could just add it to the bottom of the "accepted" list:

>* Other permissive license, accepted for dependencies when there's no MIT-licensed alternative (Apache License version 2.0)

Thank you for your opinions. :)

**Comment by dhodder** [comment]
`CONTRIBUTING.md` now confirms that Apache License 2.0-only dependencies are fine.
