### ISSUE TITLE
Deal with exit codes more consistently and composably

### ISSUE THREAD

**Issue by brson** [uutils/coreutils#211]
Right now the responsibility for setting the process exit code is scattered across many places, some utils handle it one way, some another. Non-local behavior is everywhere, and this makes it hard for the `uutils` driver to deal with exit codes.

A proposal: pass error codes as return values instead of setting the exit code and/or crashing.

1) Only the driver sets the exit code.

Main functions will look like:

```
#[allow(dead_code)]
fn main() {
    os::set_exit_status(uumain(os::args()));
}

pub fn uumain(args: Vec<String>) -> int {
}
```

and the `uutils` driver calls a bunch of `uumain` functions and gets exit codes in return.

2) All `crash!` calls get converted to `fail!`; some should be updated in the future to propagate the errors instead.

3) `show_error!` stops setting the exit code and current users are changed to return exit codes.

Although the `uumain` function needs to return an int, internally utils might want to use `Result<(), int>`.

**Comment by knight42** [comment]
* [x] Only the driver sets the exit code.
* [ ] ~~All `crash!` calls get converted to fail!; some should be updated in the future to propagate the errors instead.~~ 
Now `crash!` calls `show_error!` at first, then set the exit code. I just grep the project's code and it turned out that most calls of `crash` will set the exit code to 1. I think that's ok.
* [x] `show_error!` stops setting the exit code and current users are changed to return exit codes.
