### ISSUE TITLE
GNU tests should show the improvements/regressions

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2287]
Currently, we should the current run results:
![image](https://user-images.githubusercontent.com/733326/119787041-13872b80-bed1-11eb-8249-bab10441beed.png)

we should add information like
+X for pass
-Y for fail

etc

We are storing the history of the results here:
https://github.com/uutils/coreutils-tracking/blob/main/gnu-result.json

The code is in:
https://github.com/uutils/coreutils/blob/master/.github/workflows/GNU.yml#L49-L74

**Comment by miDeb** [comment]
Maybe it could also show which tests improved/regressed?

**Comment by sylvestre** [comment]
great idea but harder to implement :)

**Comment by blesson3** [comment]
For iterative contributions focused on improving the GNU tests PASS/FAIL ratio, the GNU GitHub actions workflow runs pretty long (avg: >1h). As a contributor, It would be nice to be able to make a change and more quickly test on the GNU action to see improvements on testing.

I'm working on an improve GNU action workflow that reasonably caches certain things so that the runs are quicker. Not sure if you're interested in my putting a PR in for that, but I'm working on it for my own testing against GNU test-suite anyway.

I tried building the tests locally using the scripts `util/build-gnu.sh` and `util/run-gnu-test.sh`, but I keep running into too many errors (see system info below). Maybe it's worth focusing on improved local testing, but the gh-actions method seems to work consistently. Let me know if you'd like me to post some of the errors I'm getting locally (in a separate issue).

```sh
$ sw_vers
ProductName:    macOS
ProductVersion: 11.2.3
BuildVersion:   20D91
$ uname -m                       
x86_64
```

**Comment by sylvestre** [comment]
> For iterative contributions focused on improving the GNU tests PASS/FAIL ratio, the [GNU GitHub actions workflow](https://github.com/uutils/coreutils/blob/master/.github/workflows/GNU.yml) runs pretty long (avg: >1h). As a contributor, It would be nice to be able to make a change and more quickly test on the GNU action to see improvements on testing.

On my system, locally, it is much faster but yeah, it is slow.

> I'm working on an improved GNU action workflow that reasonably caches certain things so that the runs are quicker (at least for an aggressively cached dev run). Not sure if you're interested in my putting a PR in for that, but I'm working on it for my own testing against GNU test-suite anyway.

Excellent news! Please share it when you have a chance!

> I tried building the tests locally using the scripts `util/build-gnu.sh` and `util/run-gnu-test.sh`, but I keep running into too many errors (see system info below). Maybe it's worth focusing on improved local testing, but the gh-actions method seems to work consistently. Let me know if you'd like me to post some of the errors I'm getting locally (in a separate issue).

Yeah, these scripts are mostly Linux focused (and probably same for upstream). So, it is expected that it isn't working as well on Mac
