### ISSUE TITLE
`more`: path of next file should be shown at the end of a file

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#2318]
Take for instance `more CONTRIBUTING.md LICENSE`. At the end of `CONTRIBUTING.md`, the prompt should show:
```
--More--(Next file: LICENSE)
```
It currently shows:
```
--More--(100%)
```

**Comment by hbina** [comment]
Can I request another change? Instead of prefixing the content with

```
::::::::::::::
FILE
::::::::::::::
```

Just write something like `Current file: FILE` in the bottom prompt.

I was genuinely confused by the presence of the text at first, and its kinda annoying that it looks like the actual content. Plenty of resources have ASCII art at the top too.
