### ISSUE TITLE
`du`: Make size-related tests filesystem specific

### ISSUE THREAD

**Issue by Funky185540** [uutils/coreutils#2478]
Some tests to the `du` utility explicitly test for an expected filesize. Currently, the expected output of these tests is gated through a series of platform-specific `cfg` statements to account for differences in expected file sizes (due to different default filesystems on these platforms).

However, these differences originate in the filesystems where the tests are executed (because of different inode sizes) and thus could vary even across hosts of the same platform. The tests should be performed dynamically, otherwise unexpected test failures occur on some hosts.

See [here](https://github.com/uutils/coreutils/blob/41d289377b5f59d435ef626e39e524d3b9eb9161/tests/by-util/test_du.rs#L573) for an example in the tests.

*Note*: It seems that the C coreutils don't test the `--bytes` option for `du` in the first place: [link](https://github.com/coreutils/coreutils/tree/master/tests/du)

**Comment by jhscheer** [comment]
Hi,
thanks for reporting this.

You mentioned you have this issue on linux, however the test `test_du_bytes` you mentioned here https://github.com/uutils/coreutils/pull/2445#issuecomment-874103652  is already a dynamic test for linux, i.e. the stdout of the `du` in `$PATH` is compared against the stdout of `uu_du`.
Please run `du --version` and post the relevant info.
If your `du` is a current version of GNU coreutils, the problem is not with the tests, but with the implementation of the `--bytes` flag in `uu_du`.

**Comment by Funky185540** [comment]
Interesting, I completely missed that linux-specific block... What puzzles me is that the "expected" value exactly matches [this one here][1].

Here's the output of `du --version`

```
$ du --version
du (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjorn Granlund, David MacKenzie, Paul Eggert,
and Jim Meyering.
```


[1]: https://github.com/uutils/coreutils/blob/41d289377b5f59d435ef626e39e524d3b9eb9161/tests/by-util/test_du.rs#L584

**Comment by Funky185540** [comment]
Think I found the issue, the test doesn't return on linux hosts after the dynamic comparison. See #2481, that fixes the issue on my machine. I also made sure that the dynamic test runs by intentionally inserting a failing assert (for testing purposes).
