### ISSUE TITLE
seq: cannot specify -s argument without a space

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#2729]
In GNU `seq`, the `-s` option accepts an argument and that argument can be provided with or without whitespace between the "-s" and the argument:
```
$ seq -s , 2
1,2
$ seq -s, 2
1,2
```
However, our version requires a space between the option and its argument:
```
$ ./target/debug/coreutils seq -s , 2
1,2
$ ./target/debug/coreutils seq -s, 2
seq: invalid floating point argument: '-s,'
Try './target/debug/coreutils seq --help' for more information.
```
Is there a way to configure the `clap` argument parsing library to allow argument without spaces?

**Comment by HeroicKatora** [comment]
I would like to work on this. The `clap` parser does allow short options to receive arguments like shown, however this style clashes with its implementation of `AllowHyphenValues`, which overrides this. The sequences goes then like shown:

<details>
<summary> `Parser::get_matches_with: After parse_short_arg MaybeHyphenValue` </summary>

```text
$ ./target/release/seq -s, 2
[            clap::build::app] 	App::_do_parse
[            clap::build::app] 	App::_build
[            clap::build::app] 	App::_propagate:./target/release/seq
[            clap::build::app] 	App::_check_help_and_version
[            clap::build::app] 	App::_propagate_global_args:./target/release/seq
[            clap::build::app] 	App::_derive_display_order:./target/release/seq
[         clap::parse::parser] 	Parser::get_matches_with
[         clap::parse::parser] 	Parser::_build
[         clap::parse::parser] 	Parser::get_matches_with: Begin parsing 'RawOsStr("-s,")' ([45, 115, 44])
[         clap::parse::parser] 	Parser::get_matches_with: Positional counter...1
[         clap::parse::parser] 	Parser::get_matches_with: Low index multiples...false
[         clap::parse::parser] 	Parser::possible_subcommand: arg=RawOsStr("-s,")
[         clap::parse::parser] 	Parser::get_matches_with: sc=None
[         clap::parse::parser] 	Parser::parse_short_arg: short_arg=RawOsStr("s,")
[         clap::parse::parser] 	Parser::parse_short_args: contains non-short flag
[         clap::parse::parser] 	Parser::get_matches_with: After parse_short_arg MaybeHyphenValue
```

</details>


In any case, the GNU implementation for `seq` to determine whether an argument is 'a number' and thus interpreted as the start of values instead of an option is very specific in that it merely looks at the first two characters. Therefore I plan to customize the argument parsing such as to emulate this first, and get rid of the `AllowHyphenValue` use in `AppSetting` in the process. This shouuld then align the parser to GNU's usage more closely.

**Comment by tertsdiepraam** [comment]
I think the solution is much simpler than that. The `Arg::number_of_values(1)` call implicitly sets `Arg::multiple_values` to true, even though it only accepts 1 argument. This disables the possibility to have a space between the flag and the argument. So the  solution would just be to remove the `number_of_values(1)` call(s).

**Comment by HeroicKatora** [comment]
I'm afraid not. These three tests are hard to fulfill at the same time:

```rust
#[test]
fn test_accepts_option_argument_directly() {
    new_ucmd!()
        .arg("-s,")
        .arg("2")
        .succeeds()
        .stdout_is("1,2\n");
}

#[test]
fn test_option_with_detected_negative_argument() {
    new_ucmd!()
        .arg("-s,")
        .args(&["-1", "2"])
        .succeeds()
        .stdout_is("-1,0,1,2\n");
}

#[test]
fn test_negative_number_as_separator() {
    new_ucmd!()
        .arg("-s")
        .args(&["-1", "2"])
        .succeeds()
        .stdout_is("1-12\n");
}
```

**Comment by tertsdiepraam** [comment]
Ah sorry, I got this all wrong indeed. Forget everything I said :)
