### ISSUE TITLE
An unexpected result is displayed in the sort result.

### ISSUE THREAD

**Issue by yyc1013721538** [uutils/coreutils#2736]
When I sort the use cases using "sort"：
[root@localhost kmod]# cat test
1.2.a.6
1.10.b.4
1.0.c.5
[root@localhost kmod]# sort -n -t'.'-k3,3 -k4,4 test
1.10.b.4
1.0.c.5
1.2.a.6
It looks like the third column is alphabetic, and I added the -n option, which was ignored, but I used -k to specify the third column as the first priority. Is this result conflicting and consistent with the expected design?

coreutils version 8.32

**Comment by jhscheer** [comment]
Maybe you'll find an answer to your question in the [manual](https://www.gnu.org/software/coreutils/manual/html_node/sort-invocation.html#sort-invocation).

However, it sounds like you might've mixed up the repos. This is not the repo for [GNU coreutils](https://github.com/coreutils/coreutils).
If that's not the case, please clarify your question because both GNU's sort and our sort behave the same for the test case you provided:

```bash
$ cargo run -p "uu_sort" --no-default-features -- -n -t'.' -k3,3 -k4,4 test
1.10.b.4
1.0.c.5
1.2.a.6
```
```bash
$ gsort -n -t'.' -k3,3 -k4,4 test
1.10.b.4
1.0.c.5
1.2.a.6
```

**Comment by miDeb** [comment]
This is indeed the expected output. Let me explain:
- By adding the `-n` option, the `-n` option is applied to all keys (`-k`) that do not have an option themselves. This means that we first look at the third column and sort it numerically. Numerical sort treats everything that is not a number as `0`, but since all lines don't have a number in the third column they all compare equal.
- Next, we look at the next key and compare the fourth columns numerically. All lines have different numbers in the fourth column so this is how they are ordered in the output.
- If there some numbers in the fourth column were also equal, we would apply a "last resort" comparison and compare the whole lines alphabetically (this can be turned off with the `-s option). For this specific case this last step is not necessary however.

We can look at the output of `sort --debug` to confirm this:
```plaintext
1.10.b.4
     ^ no match for key
       _
________
1.0.c.5
    ^ no match for key
      _
_______
1.2.a.6
    ^ no match for key
      _
_______
```

**Comment by yyc1013721538** [comment]
> This is indeed the expected output. Let me explain:
> 
> * By adding the `-n` option, the `-n` option is applied to all keys (`-k`) that do not have an option themselves. This means that we first look at the third column and sort it numerically. Numerical sort treats everything that is not a number as `0`, but since all lines don't have a number in the third column they all compare equal.
> * Next, we look at the next key and compare the fourth columns numerically. All lines have different numbers in the fourth column so this is how they are ordered in the output.
> * If there some numbers in the fourth column were also equal, we would apply a "last resort" comparison and compare the whole lines alphabetically (this can be turned off with the `-s option). For this specific case this last step is not necessary however.
> 
> We can look at the output of `sort --debug` to confirm this:
> 
> ```
> 1.10.b.4
>      ^ no match for key
>        _
> ________
> 1.0.c.5
>     ^ no match for key
>       _
> _______
> 1.2.a.6
>     ^ no match for key
>       _
> _______
> ```

Thank you, but I think I did find the wrong repo for gnu coreutils, 
and I'll ask again at gnu coreutils to push this question.
