### ISSUE TITLE
ls: argument of `--color=` is not completed

### ISSUE THREAD

**Issue by equal-l2** [uutils/coreutils#2737]
On GNU ls (`gls`), the argument for `--color=` can be completed as follows:
```zsh
% gls --color=
always  auto    never
```

On uutils' ls, this doesn't happen.

**Comment by miDeb** [comment]
This is probably because we are not specifying ` possible_values` for the `color` option here: https://github.com/uutils/coreutils/blob/a05628f01852bd1f1a4e3b979a963e83d232d0fb/src/uu/ls/src/ls.rs#L1110 We would have to add them like we do [a few lines below](https://github.com/uutils/coreutils/blob/a05628f01852bd1f1a4e3b979a963e83d232d0fb/src/uu/ls/src/ls.rs#L1125).

**Comment by equal-l2** [comment]
Thank you for pointing that out.
Can I make a PR for this issue?

**Comment by miDeb** [comment]
Sure, go ahead :)
