### ISSUE TITLE
uutils: Non-standard output and options?

### ISSUE THREAD

**Issue by kimono-koans** [uutils/coreutils#2837]
What is the community's opinion on non-standard default output from uutils?  Invoking 'ls --color,' the default color option, does not follow the GNU semantics on '->' links (it colors the target link).  This, and other examples, could be a really nice additions to any utility, but could also complicate debugging, or be confusing.  Should this behavior be another option like '--color=extra' or should we accept non-standard, but perhaps better, output in all utils?

What is the community's opinion re: non-standard options, but enhanced capability options?  For example, see: https://github.com/uutils/coreutils/issues/2836

**Comment by Bryce-MW** [comment]
I really like having utilities that have some colored output. I don't know if following how GNU does colors exactly is important since colors are probably only used for users, not read by other programs. If we did want that, I think having an option like `--color=extra` where we can go wild with colors would be good. I would be interested in adding colors to some of the utilities if we agreed on a flag for asking for those non-standard colors (maybe even making them default for tty output?).

**Comment by tertsdiepraam** [comment]
I think this conversation is better continued as a GitHub discussion.

The current consensus seems to be:
1. We don't add features that break compatibility.
2. We do sometimes "extrapolate" features (i.e. adding `b3sum` because GNU already has `b2sum`)
3. When there is a high demand, we can add extra flair (colors, progress bars, etc.), but these will be opt-in.
4. We will create a page in the docs clearly stating all the non-standard features (currently being worked on in https://github.com/uutils/coreutils/pull/3903)

**Comment by sylvestre** [comment]
Excellent summary ;)
