### ISSUE TITLE
Installing `cargo-udeps` takes very long in the CI

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#2889]
The CI builds `cargo-udeps` from source every time for all 3 platforms for which we test it. This can take up to 20 minutes (see for example https://github.com/uutils/coreutils/runs/4843132122?check_suite_focus=true). The output of the CI says:
```
Tool cache is disabled in the Action inputs, skipping it
Falling back to the `cargo install` command
```
Maybe we could enable that tool cache to speed this up a bit?

**Comment by tertsdiepraam** [comment]
To be fair, in other PR's it seems to take 7-11 minutes. But I feel like that's still quite long.

**Comment by sylvestre** [comment]
hmm, it should not block the builds?!
are you sure?

**Comment by tertsdiepraam** [comment]
Oh I guess that's just an artifact of multiple PRs fighting for CI time at the moment then.

**Comment by sylvestre** [comment]
maybe we can change the priority in GH action?!

**Comment by rivy** [comment]
I disabled the tool cache use (back in aba1c8f596) because of errors and a [languishing issue](https://github.com/actions-rs/install/issues/12) to repair them.

It looks like fixing the problem is still not on the near-term agenda.

In the meanwhile, I probably could create a repository with compiled tools to act as a cache, downloading a prefab version of `cargo-udeps` from that repo. It would like shave 5 mins (maybe a bit more) off of all the `Style/deps` CI steps.

**Comment by tertsdiepraam** [comment]
Hmm, that seems a bit too complicated for what it would gain us. If there isn't really a simple solution I'll just close this issue.
