### ISSUE TITLE
artifacts did not get published for 0.0.9 release

### ISSUE THREAD

**Issue by chenrui333** [uutils/coreutils#2892]
👋  Looks like the 0.0.9 still does not get marked as the latest release yet, as result, there are artifacts for it. Thanks!

**Comment by tertsdiepraam** [comment]
Hi, thanks for reporting this! @sylvestre was this because of the stdbuf issue? Or did something go wrong with the publish script?

**Comment by sylvestre** [comment]
Not sure what happened. Push a tag was enough in the past.
I did it by hand
https://github.com/uutils/coreutils/releases/tag/0.0.9

**Comment by tertsdiepraam** [comment]
The release currently only has the source code artifacts, not the pre-built executables. Can we fix that somehow?

It looks like it failed to build in the last commit on the 0.0.9 tag, because of stdbuf. Maybe that's why it didn't release? Would it make sense to backport the stdbuf fix to 0.0.9 (with the previous MSRV) and release a 0.0.10? Because that wouldn't require workarounds in all the build scripts like the one this issue was mentioned in (https://github.com/Homebrew/homebrew-core/pull/93303).

**Comment by sylvestre** [comment]
In the past, they were automatically generated and integrated in the release.

**Comment by rivy** [comment]
Nothing is generated/published unless all the tests pass.

**Comment by rivy** [comment]
I'll try to look into an easier, tool-based, publishing method (probably using `cargo-workspaces`) this weekend.
Hopefully, I can design something that gives feedback and blocks/warns if it can't fully complete correctly.

@sylvestre , would you mind adding "uutils/Maintainers" as co-owner to your solo-owned uutil crates ('findutils', `uu_basenc`, `uu_chcon`, `uu_csplit`, `uu_dd`, `uu_pr`, and `uu_runcon`) so that I can push to them? (It's done with "Add owner" under the "Settings" tab for the crate.)

**Comment by rivy** [comment]
> It looks like it failed to build in the last commit on the 0.0.9 tag, because of stdbuf. Maybe that's why it didn't release? Would it make sense to backport the stdbuf fix to 0.0.9 (with the previous MSRV) and release a 0.0.10? Because that wouldn't require workarounds in all the build scripts like the one this issue was mentioned in ([Homebrew/homebrew-core#93303](https://github.com/Homebrew/homebrew-core/pull/93303)).

Instead of back-porting, it's probably easiest to just call "0.0.8" the pre-MSRV-change release and just push another working release. If we sync all the crate/sub-crate versions, (ie, for coreutils, uu_\*, and uucore\* crates), the next patch version would be `0.0.12`.

Is there any reason not to sync them?

**Comment by tertsdiepraam** [comment]
> Instead of back-porting, it's probably easiest to just call "0.0.8" the pre-MSRV-change release and just push another working release.

That works too! I also think syncing them is a good idea.

**Comment by rivy** [comment]
@sylvestre , I've got a `0.0.12` release (all crates synchronized) cooking in CI. 

If you have no objections, then once it passes, I'll push it to 'main'. That will fix the "release".

Then, you (or I) can publish it from that commit.

**Comment by sylvestre** [comment]
> Is there any reason not to sync them?

Legacy :)

> would you mind adding "uutils/Maintainers" as co-owner to your solo-owned uutil crates on crates.io ('findutils', uu_basenc, uu_chcon, uu_csplit, uu_dd, uu_pr, and uu_runcon) so that I can push to them? 

Ah, bizarre why you aren't listed yet. Anyway, invites sent!

All of that sounds great, thanks :)

**Comment by rivy** [comment]
[0.0.12 is released](https://github.com/uutils/coreutils/releases/tag/0.0.12) and available (including all binary artifacts).

@sylvestre , if you'll publish it to crates.io, we'll be caught up.

**Comment by tertsdiepraam** [comment]
I wrote some release notes for this release based on GitHub's "generate release notes" feature here: https://github.com/uutils/coreutils/releases/tag/0.0.12. I can remove them if you don't like them.

**Comment by rivy** [comment]
Looks great. 👍

**Comment by sylvestre** [comment]
Terrific, thanks :)

**Comment by sylvestre** [comment]
done:
https://crates.io/crates/coreutils

**Comment by sylvestre** [comment]
Great team work ;)

**Comment by rivy** [comment]
> I'll try to look into an easier, tool-based, publishing method (probably using `cargo-workspaces`) this weekend. Hopefully, I can design something that gives feedback and blocks/warns if it can't fully complete correctly.

@sylvestre , @tertsdiepraam , after looking into this, I think I can design some scripts and instructions around `cargo-workspaces`, `gh` (GitHub CLI client), and `jq` to more simply automate releases. I'll start looking into a full design and PR when I get some time, hopefully over the next couple of weeks...
