### ISSUE TITLE
cksum: failing GNU tests

### ISSUE THREAD

**Issue by jtracey** [uutils/coreutils#2930]
The latest version of GNU's tests add `tests/misc/cksum`, `tests/misc/cksum-a`, `tests/misc/cksum-c`, and `tests/misc/sm3sum`, all of which currently fail. This will track the respective problems from each.

**Comment by str4d** [comment]
I suspect that this is because `uu_cksum` currently only takes file arguments, and does not implement any of the necessary options. The [GNU Coreutils 9.0 docs for `cksum`](https://www.gnu.org/software/coreutils/manual/html_node/cksum-invocation.html#cksum-invocation) list the following options:
- [ ] `-a/--algorithm`
- [ ] `--debug`
- [ ] `--untagged`
- All options [supported by `b2sum`](https://www.gnu.org/software/coreutils/manual/html_node/b2sum-invocation.html):
  - [ ] `-l/--length`
  - All options [supported by `md5sum`](https://www.gnu.org/software/coreutils/manual/html_node/md5sum-invocation.html):
    - [ ] `-b/--binary`
    - [ ] `-c/--check`
    - [ ] `--ignore-missing`
    - [ ] `--quiet`
    - [ ] `--status`
    - [ ] `--tag`
    - [ ] `-t/--text`
    - [ ] `-w/--warn`
    - [ ] `--strict`
    - [ ] `-z/--zero`

**Comment by str4d** [comment]
Investigating the codebase a bit further, I see that both `md5sum` and `b2sum` are implemented via `hashsum`. This suggests we should make `cksum` also be implemented by `hashsum`. I've checked off above all the options currently implemented by `hashsum`.

**Comment by str4d** [comment]
Looks like `test/misc/b2sum` is also failing, both because `hashsum` doesn't support `-l/--length`, and `cksum` doesn't support `-a blake2b`.

I'm going to try implementing this.

**Comment by str4d** [comment]
I made a bunch of progress on this and then ran out of time to finish the PRs. Picking this back up now; I'll rebase my current local work and get some initial PRs up.

**Comment by str4d** [comment]
Ugh, this is annoying: `b3sum` was added in https://github.com/uutils/coreutils/pull/3108, and its corresponding [upstream binary](https://github.com/BLAKE3-team/BLAKE3/tree/master/b3sum) defines `-l/--length` in bytes, whereas GNU Coreutils `b2sum` defines `-l/--length` in bits.

There are three options here:

- Define `-l/--length` as bytes to match upstream `b3sum`. Given that compatibility with GNU Coreutils is being prioritised (per this issue), I think that would not be considered acceptable as `b2sum` would then never pass GNU tests.
- Define `-l/--length` as bits to match GNU Coreutils. I _really_ dislike this option, for two reasons:
  - `--length` being bits means it needs to be a multiple of 8, so 7/8 of values that upstream `b3sum` accepts will be rejected here. That's not so bad, it makes the difference discoverable.
  - In the cases where an upstream length is a multiple of 8, `b3sum` here would output 1/8 of the length, e.g. instead of a 16-byte hash the user gets a 16-bit hash (2 bytes). This is a **TERRIBLE** silent security issue.
- Define `-l/--length` as bits when used with `b2sum` or `cksum`, and bytes when used with `b3sum`. This is awful for UX; in particular, it is undefined how `hashsum` should treat it. The least-bad option might be to just special-case the byte interpretation to `b3sum`, and not allow it to be used with `-a blake3` on `hashsum` (otherwise `hashsum` would almost certainly end up conflicting with `cksum` if the latter adds BLAKE3 support).

We have a somewhat-similar issue in that `hashsum` itself defines a separate `--bits` flag for its SHA3 and SHAKE support, which is effectively duplicative of GNU Coreutils `-l/--length`. I'm not going to try solve that here.

**Comment by str4d** [comment]
cc @oconnor663 who wrote `b3sum`

**Comment by sylvestre** [comment]
While I really want GNU's compatibility, we workaround with upstream testsuite from time to time. See
https://github.com/uutils/coreutils/blob/main/util/build-gnu.sh#L121=
and below

**Comment by tertsdiepraam** [comment]
Note that the suprising behaviour you mentioned in option 2 not only happens between b3sum implementations but also between different hashing algorithms. I.e. if I use the external b3sum first and then (GNU) b2sum, then the length does not match either. Hence, I think we bring back the consistency and should build what a hypothetical GNU b3sum would look like, not what another b3sum already does, to ensure compatibility/consistency with GNU and with the other utils in uutils.

I like the first option too, but it would indeed break GNU compatibility, so like Sylvestre mentioned, we'd have to work around the tests. Not to mention that it could be surprising for GNU users (although we'd err on the secure side).

**Comment by oconnor663** [comment]
Yeah, the inconsistency blows. Here are some scattered thoughts about why it ended up the way it is:

- Unfortunately, different BLAKE2 interfaces have been inconsistent for a long time. CLIs and written naming conventions tend to use bits, but Python's `hashlib.blake2b` API takes the `digest_size` parameter in bytes. Similarly, C APIs usually take a `size_t` somewhere that counts bytes.

- Measuring BLAKE2 output in bits makes sense from a security perspective. The security properties of BLAKE2b-512 and BLAKE2b-256 mirror those of SHA-512 and SHA-256. However, this relationship relies somewhat on BLAKE2b not allowing output sizes larger than its internal state size. For example, `b2sum -l 1024` will just error out. The same doesn't apply to BLAKE3, though, which has a built-in XOF that'll give you as many output bytes as you like. "BLAKE3-512" (if we were to call it that) does _not_ provide more security than the default 256-bit BLAKE3. I find this is a common source of confusion, so I discourage naming BLAKE3 instances in terms of bits, even though it can make sense on the small end.

- Similarly, and again like SHA-512 and SHA-256, BLAKE2b-512 and BLAKE2b-256 are independent ("domain separated") hash functions. Changing the output length gives you a completely different hash. This is a natural design for those functions, since they can mix the output length in initialization one way or another. But for an XOF like BLAKE3, it's pretty common for the output length to be "who knows, we're gonna use this as a stream cipher", so domain-separating outputs of different lengths isn't always possible. Rather than having two modes for this, as BLAKE2X did, in BLAKE3 shorter outputs are always prefixes of longer ones. This is another reason why I discourage bit-counting names like "BLAKE3-512".

Which is all to say, that when there's a choice between counting bits and counting bytes, BLAKE3 pretty strongly prefers to count bytes. It keeps CLIs and library APIs consistent with each other, and it avoids some common points of confusion. But sometimes there isn't a choice, like our situation here, and then we suffer some inconsistency.

**Comment by tertsdiepraam** [comment]
Interesting! That does make it clearer as to why b3sum is different. Maybe a solution could be to make a split API. So b2sum (and the other ones GNU supports) would accept a `--bits` option and `-l` would work but be deprecated/hidden. b3sum would accept a `--bytes` option and using the wrong argument would result in an error.

**Comment by oconnor663** [comment]
If you all decide to do something like `--bytes`, it might be reasonable to add a similar option upstream on `b3sum`, so that there's at least _something_ we could tell people to do that'll work (or give a clear error message) everywhere?

**Comment by sergeevabc** [comment]
Current `coreutils b3sum` generates `hash *filename`, but the original implementation by @oconnor663 uses a second space instead of an asterisk and refuses to check hashes if such character is missing as follows
```
$ b3sum -c B3SUMS
b3sum: Invalid space
b3sum: WARNING: 3 computed checksums did NOT match
```
We need to either discuss it or bring this part of `coreutils` into line.

**Comment by jtracey** [comment]
It would appear this was fixed via #6499.

**Comment by sergeevabc** [comment]
Another mess here:

```console
$ coreutils.exe 
coreutils 0.0.30 (multi-call binary)

$ coreutils.exe b3sum coreutils.exe
0755ad0a3492592f566d90acb6df93c4087d3bedda4915912dba036d815d0605 *coreutils.exe

BUT

$ coreutils.exe b3sum C:\coreutils.exe
\0755ad0a3492592f566d90acb6df93c4087d3bedda4915912dba036d815d0605 *C:\\coreutils.exe
^ WTF???

$ b3sum.exe C:\coreutils.exe
0755ad0a3492592f566d90acb6df93c4087d3bedda4915912dba036d815d0605  C:/coreutils.exe
```

**Comment by oconnor663** [comment]
@sergeevabc `b3sum` normalizes backslashes to forward slashes so that `b3sum --check` on a Unix machine has a reasonably good chance of accepting a `b3sum` output from a Windows machine. This also has consequences for e.g. Unicode/`OsStr` handling. We have a doc about it: https://github.com/BLAKE3-team/BLAKE3/blob/master/b3sum/what_does_check_do.md

My understanding of forward slashes on Windows is that they're always(?) valid in place of backslashes at the API level, even though some higher level applications choke on them (particularly `cmd.exe`). So even though there's code in `b3sum` to convert backslashes to forward slashes, there is no conversion in the other direction; after maybe unescaping newlines, `--check` opens filepaths verbatim.
