### ISSUE TITLE
GNU utilities match unambiguous prefixes of long options but uutils utilities don't

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#2931]
I'm testing with GNU coreutils v8.30

The GNU utilities seem to have a feature where a long option is inferred from an unambiguous prefix. For example:
```
$ seq -s : --e 10
01:02:03:04:05:06:07:08:09:10
$ seq -s : --eq 10
01:02:03:04:05:06:07:08:09:10
$ seq -s : --equ 10
01:02:03:04:05:06:07:08:09:10
$ seq -s : --equa 10
01:02:03:04:05:06:07:08:09:10
$ seq -s : --equal 10
01:02:03:04:05:06:07:08:09:10
$ seq -s : --equal- 10
01:02:03:04:05:06:07:08:09:10
$ seq -s : --equal-wid 10
01:02:03:04:05:06:07:08:09:10
$ seq -s : --equal-widt 10
01:02:03:04:05:06:07:08:09:10
$ seq -s : --equal-width 10
01:02:03:04:05:06:07:08:09:10
```
And an ambiguous prefix results in a usage error message. For example:
```
$ split --lin 10
split: option '--lin' is ambiguous; possibilities: '--lines' '--line-bytes'
Try 'split --help' for more information.
```

This is causing test errors in the GNU test suite. One that I found is in `tests/split/suffix-auto-length.sh`. In that test, `split --numeric` is used, but the full name of the long option is `--numeric-suffixes`.

**Comment by tertsdiepraam** [comment]
That's right! This issue had been blocked for a long long time, because it required a change to clap, so I opened a PR there(https://github.com/clap-rs/clap/pull/2525) to add [`AppSettings::InferLongArgs`](https://docs.rs/clap/latest/clap/enum.AppSettings.html#variant.InferLongArgs). But clap took a long time to release version 3 and so we had to wait, but now we are using clap 3, so this is now possible.

As a workaround we also had some aliases of shorter names, so those should be removed once `InferLongArgs` is added.
