### ISSUE TITLE
`od` help page doesn't have usage example

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2991]
https://uutils.github.io/coreutils-docs/user/utils/od.html

it should have the same as `numfmt [OPTIONS]` in https://uutils.github.io/coreutils-docs/user/utils/numfmt.html

**Comment by crazystylus** [comment]
Hi @sylvestre,
Can you confirm if `od [OPTION]... [--] [FILENAME]...` is needed or only `numfmt [OPTIONS]` is needed to be printed as the first line in USAGE string of od is `od [OPTION]... [--] [FILENAME]...`?

Currently usage is not printed because `USAGE string` starts with a newline and uudoc only considers 1st line for USAGE section in docs

**Comment by tertsdiepraam** [comment]
`od [OPTION]... [--] [FILENAME]...` would be best I think. You could also take a look at the doc generation to support multiline usage strings, but that might be quite complex.

**Comment by crazystylus** [comment]
I think adding multi-line support to doc generation can be taken up separately.In the linked PR I have removed the newline from starting of string which is causing empty line in doc.

Please let me know if I need to make any changes to the attached PR?
