### ISSUE TITLE
Question: Makefile, GNUmakefile & Makefile.toml

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#3138]
We currently have 3 makefile-like files:
- `Makefile`
- `GNUmakefile`
- `Makefile.toml`

The `Makefile` just ensures that GNU `make` is used and then refers to `GNUmakefile` and the `Makefile.toml` is for `cargo make`. So my question is: do we need all of these?
- I tried to run the `GNUmakefile` with a non-gnu `make` (NetBSD) and it seemed to work just fine, so can we just use `Makefile` or are there any GNU extensions we're using?
- `cargo make` is handy, but the usage is undocumented, so I'm not sure how much it's used. I was actually surprised to see that most of the commands in there still work, because the last commit is 2 years old. Can we remove this without losing functionality? And if not, can we port some commands to normal `make` instead to remove the duplication? @rivy, you have made most (all?) commits to that file. Are you still using it?

**Comment by rivy** [comment]
@Arcterus had the *Makefile*/*GNUmakefile* set up when I came on board. I haven't really touched it much other than to add and keep a bit of basic WinOS support so that at least a quick `make` would work.

From the *Makefile* setup, I assume @Arcterus wanted to force use of `gmake` to avoid surprises between platforms.

Personally, I usually use `cargo ...` directly and depend on CI for most things these days.

But I set up `cargo make` as builder which was platform portable and friendly to new devs/users (including me at the time 😃; see `cargo make help`). It is a bit more generally capable/flexible than *GNUmakefile*, allowing use of the util scripts and features to automatically and dynamically determine build content (the makefile is hard-coded). I got distracted by other project considerations never took the time to add it to the README on top of the standard `cargo ...` instructions. But, it could be noted as a third build method for newer devs/users.

That being said, `cargo make ...` certainly hasn't taken off as the top cross-platform builder in this space, and I'd be happy if we could combine it all into `make`. But the makefile is only partially WinOS compatible at the moment. And `make` is crufty. Porting all the *Makefile.toml* capability to the *GNUmakefile*, while certainly possible, is complicated and will take some significant coding time and machinations to get a working, friendly, and cross-platform product. I have built a couple for some C/C++ projects if someone wants a reference to take a crack at it.

I would love a more capable, cross-platform, and friendly builder if someone can find/build something. I just haven't found it yet.

**Comment by tertsdiepraam** [comment]
Thanks!

The Windows support is something I hadn't considered yet. That's indeed something to keep in mind.

> Personally, I usually use cargo ... directly and depend on CI for most things these days

Yeah, me too, but it's not ideal. I often find myself typing long commands like:
```
cargo test --no-default-features --features ls
```

The `cargo make` command for that is certainly much easier :)

> But the makefile is only partially WinOS compatible at the moment. And make is crufty. 

I definitely agree here. `make` is very crufty and it's very easy to put a unix command in there by accident, breaking the Windows build.

> I would love a more capable, cross-platform, and friendly builder if someone can find/build something. I just haven't found it yet.

There's [`just`](https://github.com/casey/just), which looks interesting, but otherwise I'm also not sure if there's anything that offers a significant improvement over `make`.

**Comment by tertsdiepraam** [comment]
Question has been answered and this doesn't bother me anymore :)
