### ISSUE TITLE
du: use UResult instead of the set_exit_code

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#3389]
tertsdiepraam: _I think this can be cleaned up some more with `UResult`, which will print the right error message automatically when converting from an `io::Error`. However, that is a more involved refactor, so I'll approve and leave it up to you whether you want to do this._

_Originally posted by @tertsdiepraam in https://github.com/uutils/coreutils/pull/3382#discussion_r846754666_

**Comment by sylvestre** [comment]
In:
https://github.com/uutils/coreutils/blob/main/src/uu/du/src/du.rs#L318=
https://github.com/uutils/coreutils/blob/main/src/uu/du/src/du.rs#L376=
https://github.com/uutils/coreutils/blob/main/src/uu/du/src/du.rs#L379=

**Comment by tertsdiepraam** [comment]
These pages from the documentation might be useful:
 - [`uucore::error`](https://docs.rs/uucore/latest/uucore/error/index.html)
 - [`uucore::error::UIoError`](https://docs.rs/uucore/latest/uucore/error/struct.UIoError.html)

**Comment by ackerleytng** [comment]
I'm interested to take this up. I'm new to rust so I'd like to understand what's idiomatic, or what refactoring we're hoping to do.

Can I perhaps let `du()` return a boolean true for "has error" and false for no error, and then reduce over all the results at the end?

Is the purpose of `du()` returning a iterator so that we only operate on included files instead of all files? Are we using an iterator instead of mapping over a vector to avoid processing files that are excluded?

**Comment by tertsdiepraam** [comment]
If I recall correctly, it doesn't need that. The reason that we want to use UResult is that it automatically shows better error messages for io errors (better as in more compatible with GNU). You can probably construct the error and then immediately print it with the `show!` macro.
