### ISSUE TITLE
Print a message if a newer version is available

### ISSUE THREAD

**Issue by beardgans** [uutils/coreutils#3426]
👋 Thank you for this awesome project 🔥

I found this feature in the [GitHub CLI application](https://github.com/cli/cli/blob/trunk/internal/update/update.go) and [npm](https://github.com/npm/cli/blob/latest/lib/utils/update-notifier.js).

I think it'll be useful for users who install `coreutils` using `cargo`.
And this will let them know that a new version is available and it's time to update.

Ready-made crates to implement that:
* https://github.com/mgrachev/update-informer
* https://github.com/tarikeshaq/update-notifier

**Comment by tertsdiepraam** [comment]
Hi! Thanks for the report! It's a very interesting idea, but I don't think we can do this for several reasons.

- The first is that we have to be very careful about what output is printed because it might be parsed by other scripts. Consider for example the troubles that would arise if somebody uses `sort` to sort some lines in a file and suddenly a message shows up saying "you should update uutils" in that file. We could print it to stderr, but that's also not ideal. At the very least, the stderr of a complex script would be polluted with these messages.
- The second reason is that we aim to make these utils as small as possible and this feature would require a lot of code to make an http request to crates.io
- It would also make the utils slower, because a request has to be made for every call, which again might not be a big deal with interactive use, but does add up in scripts.
- We have also just removed an HTTP(S) related dependency from `uudoc` (`ureq`, used by the first crate you mentioned) to ensure that uutils builds on more platforms, so we probably cannot provide this feature on all platforms.
- Lastly, uutils might be installed in a way that makes an immediate update impossible. For example, it might be packaged by some distribution. The user would then be presented with this message every time, without being able to do something about it.

So, what can we do? We could make an optional (opt-in) `check-version` command in the multi-call binary. Although I don't think that provides much value over a quick `cargo install` check. We could also document how to set up a cron job to check the version periodically. Neither option would be automatic though.

If you can think of way of implementing this without these issue, I'd be interested to hear it though!

**Comment by beardgans** [comment]
> * The first is that we have to be very careful about what output is printed because it might be parsed by other scripts. Consider for example the troubles that would arise if somebody uses `sort` to sort some lines in a file and suddenly a message shows up saying "you should update uutils" in that file. We could print it to stderr, but that's also not ideal. At the very least, the stderr of a complex script would be polluted with these messages.

As an option, we can add an additional flag `--check-updates` (or a command `check-updates`) and start checking updates only if there is this flag. I think it could help in this situation.

> * It would also make the utils slower, because a request has to be made for every call, which again might not be a big deal with interactive use, but does add up in scripts.

All of crates I mentioned in the issue can configure check frequency and have cache support to avoid a large number of requests. They can check updates once a day for example.

> * Lastly, uutils might be installed in a way that makes an immediate update impossible. For example, it might be packaged by some distribution. The user would then be presented with this message every time, without being able to do something about it.

An additional flag `--check-updates` might help in this situation. Another option - use a feature flag to disable check updates in such distributions (enabled by default).

> So, what can we do? We could make an optional (opt-in) `check-version` command in the multi-call binary.

I like this idea 👍

**Comment by tertsdiepraam** [comment]
It's been a long time since this was proposed and I think we should close this issue. I think that uutils coreutils should be installed primarily via package managers and that this feature would therefore not be necessary. It would also increase the maintenance burden, the size of the binary and compile times. I appreciate the idea, but ultimately I'm not convinced.
