### ISSUE TITLE
timeout: fails to kill child process when given as sh -c

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#3489]
Environment: Ubuntu 20.04.4, coreutils v8.30, `sh` links to `dash`

The uutils version of timeout fails to kill the child process when it is given as `sh -c "..."`.

GNU timeout:
```sh
$ timeout 1 sh -c "yes > /dev/null"
$ ps | grep [y]es
# no output, meaning no running process, as expected
```

uutils timeout:
```sh
$ ./target/release/timeout 1 sh -c "yes > /dev/null"
$ ps | grep [y]es
2458257 pts/1    00:00:02 yes
```

However, uutils timeout does correctly kill the child process when it is given directly:
```sh
$ ./target/release/timeout 1 yes > /dev/null
$ ps | grep [y]es
# no output, meaning no running process, as expected
```

This causes an orphan process in the GNU test case `tests/split/filter.sh`.

**Comment by fritzrehde** [comment]
I cannot replicate your observations, I tried the three examples you provided and found that all kill the child process correctly.

**Comment by tertsdiepraam** [comment]
Interesting, maybe this fixed it? https://github.com/uutils/coreutils/pull/4315

**Comment by fritzrehde** [comment]
Yep, I just went through the code and found that PR/commit too. It looks good to me as well.
However, I am looking at the code that tests this fix right now:
https://github.com/uutils/coreutils/blob/862a2df924eabf9c2c99dae520b1d4d78e361b57/tests/by-util/test_timeout.rs#L147-L160
and, when running locally with `cargo test --features timeout test_kill_subprocess`, the test fails, because the stderr does not contain `Terminated`. I will create a PR that fixes this and adds some documentation (since I didn't immediately understand what the test was doing and why).

**Comment by jfinkels** [comment]
Nice, I'm glad this was fixed! I'll close the issue then.
