### ISSUE TITLE
`ls -sm` is adding an unnecessary trailing space

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#3608]
With this simple test case:
```
export C=$(pwd)/target/debug/coreutils
rm -rf tempdir
mkdir tempdir
cd tempdir
seq 2000 > b
touch a

$C ls -sm a b  > out
cat <<\EOF > exp
0 a, 12 b
EOF
diff -u out exp
cd -
 -
```
Comment the first line to try with GNU's:

Result:
```
@@ -1 +1 @@
- 0 a, 12 b
+0 a, 12 b
```

**Comment by tertsdiepraam** [comment]
The extra space is inserted to align `0` with `12`, because we assumed that the sizes need to be aligned, which is true for the columns layout, but not for the comma layout.

I believe the relevant code is in this block:
https://github.com/uutils/coreutils/blob/95de5f6494dbfa7e5223479dd34c60cd2fa871b2/src/uu/ls/src/ls.rs#L1861-L1868
