### ISSUE TITLE
Add automatic conversion from `nix::Errno` to `UError` like we have for `std::io::Error`. 

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4007]
We should probably add automatic conversion from `nix::Errno` to `UError` like we have for `std::io::Error`. Then we don't need these manual conversions.

https://docs.rs/uucore/latest/uucore/error/trait.UError.html

_Originally posted by @tertsdiepraam in https://github.com/uutils/coreutils/pull/4003#discussion_r986575861_

**Comment by orhun** [comment]
Hey, I would like to work on this.

**Comment by orhun** [comment]
Can you guide me on how to implement `UError` and where to place the implementation? As far as I understood, we want to achieve something like this:

```rs
impl UError for nix::errno::Errno {
    fn code(&self) -> i32 {
        match self {
            Errno::ENOENT => {}
            Errno::EACCES => {}
            _ => {}
        }
    }

    fn usage(&self) -> bool {
        false
    }
}
```

Is that correct?

**Comment by tertsdiepraam** [comment]
We'd like something similar to the implementation for [`UIoError`](https://docs.rs/uucore/latest/uucore/error/struct.UIoError.html). The implementation of which you can find [here](https://github.com/uutils/coreutils/blob/bd5e46ab674b1e6a8f27149af8432e37284fa830/src/uucore/src/lib/mods/error.rs#L376). I think you could even make it so that the `nix::errno::Errno` is turned into a `UIoError` because they're very similar.

**Comment by orhun** [comment]
I can't access the `nix` crate from `uucore::error`, is there a feature flag that prevents this?

```
error[E0433]: failed to resolve: use of undeclared crate or module `nix`
   --> src/uucore/src/lib/mods/error.rs:512:11
    |
512 | impl From<nix::Error> for UIoError {
    |           ^^^ use of undeclared crate or module `nix`
```

I would like to implement the conversion in `error` module. Am I doing something wrong?

**Comment by tertsdiepraam** [comment]
Yeah you need to add `nix` as a dependency of `uucore`

**Comment by orhun** [comment]
I tried `#[cfg(unix)]` and `#[cfg(any(target_os = "linux", target_os = "android"))]` but no luck. Still can't access `nix` from `src/uucore/src/lib/mods`. I can access it from `src/uucore/src/lib/features` though. Also, adding `nix` as a default feature to `uucore` works but definitely not applicable I guess.

**Comment by tertsdiepraam** [comment]
Ah I see what's going on. It's an optional dependency even for unix. `cargo run --features nix` should work. However, I think we want to make it non-optional for unix systems with this change, so you can remove the `optional = true` in the `Cargo.toml`

**Comment by orhun** [comment]
Great, that worked! I have another question: There are some custom error messages such as `"cannot stat {}: No such file or directory"` in the `uumain` function that I'm refactoring. As far as I understand, we want to get rid of matching `nix::Error` and automatically map `nix` errors to `UIoError`. In that case, doing e.g. `map_err(UIoError::from)?` would return early from the function without a custom error message (due to `?` operator). Is this something we want?

**Comment by tertsdiepraam** [comment]
We do want to keep those messages, I think. We call them "context" and we have the `map_err_context` method defined for that via the `FromIo` trait. You could implement that trait for `nix::Error` as well.

**Comment by orhun** [comment]
> We do want to keep those messages, I think. We call them "context" and we have the `map_err_context` method defined for that via the `FromIo` trait. You could implement that trait for `nix::Error` as well.

Do you mean like this?

```rs
open(Path::new(&f), OFlag::O_NONBLOCK, Mode::empty()).map_err(|e| {
    e.map_err_context(|| {
        format!("cannot stat {}: No such file or directory", f.quote())
    })
})?;
```

In this case we still need to use if-else conditions for showing different messages. I'm not sure how automatic conversion helps here. What do you think?

**Comment by tertsdiepraam** [comment]
Not quite. It should just be:
```rust
open(...).map_err_context(|| format!("cannot stat {}", f.quote()))?
```

There's plenty examples in the codebase with `std::io::Error/Result` (just search for map_err_context).
