### ISSUE TITLE
`install`: Accept special files like `/dev/stdin`

### ISSUE THREAD

**Issue by TheDcoder** [uutils/coreutils#5080]
GNU coreutils accepts special files like `/dev/stdin` without any issues, for e.g.:
```
$ echo 'foo' | install /dev/stdin test
```

That creates a file called `test` with `foo\n` as its contents, which isn't surprising.

However our coreutils fail with the same usage with this error:
```
install: cannot install '/dev/stdin' to 'test': Invalid input parameter
```

This issue doesn't effect `cp`, however it might effect other utils which haven't been tested.

**Comment by TheDcoder** [comment]
Found in the wild [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=keyd#n32):
```bash
echo 'g keyd' | install -Dm644 /dev/stdin "${pkgdir}/usr/lib/sysusers.d/${pkgname%-git}.conf"
```

**Comment by tertsdiepraam** [comment]
I checked the source code and `install` just uses `std::fs::copy`, which indeed doesn't handle that case. `cp` has a more complicated procedure which falls back to copying the contents. I think it might make sense to extract that procedure to `uucore` and share it between the two utils. Could also be fun to make it a separate crate later too, because it might be useful for other projects to have a more flexible `copy` function, but let's  start with `uucore`.

**Comment by Javatrix** [comment]
Checked right now, works correctly. Perhaps the issue should be closed?

**Comment by TheDcoder** [comment]
What fixed the issue? :thinking:

**Comment by Javatrix** [comment]
I don't know, but this issue seems to be quite old. Perhaps somebody fixed it and forgot to mark this as complete.

**Comment by DaringCuteSeal** [comment]
Issue still persists apparently. The only time when it works is when I use zsh's herestring which works because zsh creates some sort of non-special temporary file I think. Piping to the command still breaks `install` though. I think `/dev/stdin` should be handled specially, kinda like how uutil's `cat` does it

**Comment by sylvestre** [comment]
Don't hesitate to provide a patch, it should not be hard

**Comment by DaringCuteSeal** [comment]
> I checked the source code and `install` just uses `std::fs::copy`, which indeed doesn't handle that case. `cp` has a more complicated procedure which falls back to copying the contents. I think it might make sense to extract that procedure to `uucore` and share it between the two utils. Could also be fun to make it a separate crate later too, because it might be useful for other projects to have a more flexible `copy` function, but let's start with `uucore`.

since this also affects `cp` i figured that i may wanna integrate a copy function into uucore

**Comment by cakebaker** [comment]
Fixed in https://github.com/uutils/coreutils/pull/6965
