### ISSUE TITLE
Update the {touch, date} code to use parse_datetime 0.5.0

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5307]
a lot of changes have been made to parse_datetime.
https://github.com/uutils/parse_datetime

The code of touch & date needs to be updated

**Comment by sylvestre** [comment]
To start, just update Cargo.toml to update the version
and to test:
```
$ cargo test --features=unix  test_touch 
$ cargo test --features=unix  test_date
```

**Comment by u8sand** [comment]
I tackled this and made the following patch which *does* pass the tests but I'm not quite satisfied.
https://gist.github.com/u8sand/f957ccf502007d068948193660736270

The main problem is that parse_datetime does not distinguish between relative/absolute datetimes, but touch has different behavior for relative/absolute (at least the tests suggest this). I think parse_datetime should be updated to allow you to make this distinction.

Maybe i'll get to it or someone else can pick it up from here, I figured I may as well share what was already done.

**Comment by sylvestre** [comment]
@philolo1 any suggestion ? :)

**Comment by tertsdiepraam** [comment]
Nice @u8sand! The idea of the `parse_datetime` API is that the difference between absolute and relative is built-in. So you give it a reference time to parse from, and if the format is relative it will do the calculations from that date. If it is absolute that reference date will be ignored. So, _in theory_, it should be as easy as this:
- get the atime and mtime,
- parse the date format twice, once with atime and once mtime as reference,
- use the time that `parse_datetime` returns.
If that doesn't work, please let us know, because that would be a bug in `parse_datetime`!

**Comment by u8sand** [comment]
@tertsdiepraam you're right, perhaps it's just premature optimization that I hoped to run parse_datetime just once. PR pending
