### ISSUE TITLE
`mktemp`: expose functionality for nushell

### ISSUE THREAD

**Issue by tskinn** [uutils/coreutils#5465]
As per https://github.com/uutils/coreutils/issues/5088#issuecomment-1733828007 I'm opening this ticket to discuss details about how expose `mktemp` functionality for use in nushell.

**Comment by tskinn** [comment]
Should a new pub fn be created that returns a result of String as I think the current functions just print to stdout. What other considerations are there?

**Comment by tertsdiepraam** [comment]
Yes, I think that's a good idea! I think it should be roughly done as follows:
- `mktemp`: returns a path and calls `exec` and `dry_exec`
- `exec` and `dry_exec` should also return the path.
- `uumain` calls `mktemp` and prints the result.

Otherwise I think this one should be fairly simple. Thanks for picking this up!
