### ISSUE TITLE
printf: incorrect exit code when passing invalid value to `%x`

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5536]
With GNU:
```
/usr/bin/printf %x %194 > /dev/null
echo $?
```
returns:
```
/usr/bin/printf: '%194': expected a numeric value
1
```
With our Rust implementation:
```
./target/debug/coreutils printf %x %194 > /dev/null
echo $? 
```
returns:
```
printf: '%194': value not completely converted
0
```

**Comment by pawelngei** [comment]
From what I was able to deduce, we're running into `warn_incomplete_conv` called in [intf.rs](https://github.com/uutils/coreutils/blob/main/src/uucore/src/lib/features/tokenize/num_format/formatters/intf.rs#L115). It only prints an error message and breaks, doesn't propagate higher.

The closest space to surface this as an `UResult` would be [sub.rs](https://github.com/uutils/coreutils/blob/main/src/uucore/src/lib/features/tokenize/sub.rs#L327), is that correct?

However, it returns `%{s}: invalid conversion specification"`, not the `expected a numeric value` from `warn_expected_numeric` in [num_format.rs](https://github.com/uutils/coreutils/blob/main/src/uucore/src/lib/features/tokenize/num_format/num_format.rs).

Being new to Rust and to the `coreutils`: what's the correct course of action here? Fire the `warn_expected_numeric` and then change the code so that the SubParser gets an Err?

**Comment by pawelngei** [comment]
Submitted a PR! However,

> ```
> printf: '%194': value not completely converted
> 0
> ```

Are you sure that the code returns the value in `'quotes'` on the current `main`? `.maybe_quote` doesn't seem to work this way for me.
