### ISSUE TITLE
csplit doesn't support precision

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5709]
With ours:
```       
$ echo > in
$ csplit -b '%0#6.3x' in 1
csplit: incorrect conversion specification in suffix
```

With GNU:
```       
$ echo > in
$ /usr/bin/csplit -b '%0#6.3x' in 1
0
1
```
The regexp here:
https://github.com/uutils/coreutils/blob/main/src/uu/csplit/src/split_name.rs#L52
and the following code needs to be updated

Tested in GNU with tests/csplit/csplit.sh

**Comment by marc-delgado-ferreres** [comment]
The issue seems to be related to the format string specification you're using with the -b option in the csplit command. The format string %0#6.3x you're using may be causing the error due to an incorrect conversion specification in the suffix.

The format string %0#6.3x seems to be attempting to specify a hexadecimal format with a certain precision, but it appears that the current implementation of csplit is not compatible with this exact specification.

To resolve the issue, you could try simplifying the format string to something more basic and compatible, such as %04d, which specifies a 4-digit number with zero padding on the left. This might avoid the error you're experiencing.

If after simplifying the format string the problem persists, you could try looking into the csplit documentation or community forums for further information on the tool's limitations and possible alternative solutions.

I hope this information helps you identify and resolve the issue. If you need further assistance, feel free to ask.

**Comment by tertsdiepraam** [comment]
@marc-delgado-ferreres Glad you asked ChatGPT for us! Really helpful! Now please don't do that again.

Anyway, I think I just fixed the issue across these two PRs:
- https://github.com/uutils/coreutils/pull/5958
- https://github.com/uutils/coreutils/pull/5955
