### ISSUE TITLE
make failed: #![feature(exit_status)] may not be used in the beta release channel

### ISSUE THREAD

**Issue by acgtyrant** [uutils/coreutils#583]
I run `make`, it returns:

	rustc -O mkmain.rs -o /home/acgtyrant/Projects/coreutils/build/mkmain
	mkmain.rs:1:1: 1:25 error: unstable feature
	mkmain.rs:1 #![feature(exit_status)]
		    ^~~~~~~~~~~~~~~~~~~~~~~~
	note: this feature may not be used in the beta release channel
	error: aborting due to previous error
	Makefile:280: recipe for target '/home/acgtyrant/Projects/coreutils/build/mkmain' failed
	make: *** [/home/acgtyrant/Projects/coreutils/build/mkmain] Error 101

**Comment by kwantam** [comment]
Currently you need to build with nightly. We are working on bringing things up to speed with changes in stdlib, and after that we'll go through and remove feature gates where possible.

**Comment by acgtyrant** [comment]
@kwantam The Rust 1.0 is out, then what version are you supporting now? I hope it is 1.0, not nightly.

**Comment by kwantam** [comment]
The issue isn't that the project specifically targets nightly, but that the code as currently written uses unstable features. The parts that use those unstable features need to be rewritten in order to allow compiling with stable rather than nightly.

The idea is that this reliance on unstable features will be removed, but it will not happen overnight. In fact, it's not guaranteed that the codebase will be rewritten for 1.0 compatibility: perhaps instead it'll be compatible with the 1.1 stable features, which are a superset of the 1.0 features.

But yes, the goal long term is to build on a stable version of the compiler.

**Comment by acgtyrant** [comment]
OK, I will help to remove unstable features.
