### ISSUE TITLE
wc.rs: Refactor to remove `#[allow(clippy::cognitive_complexity)]`

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5882]
https://github.com/uutils/coreutils/blob/main/src/uu/wc/src/wc.rs#L568

A potential way to do it:
```
    while let Some(chunk) = reader.next_strict() {
        match chunk {
            Ok(text) => process_chunk(&mut total, &text),
            Err(error) => return handle_error(error, &total),
        }
    }
```

**Comment by harshRn** [comment]
@sylvestre Hi!
My very first contribution to a Rust repo! 
I used your proposed potential solution for the fix. However, In case of `Err` when matching `chunk`, while `BufReadDecoderError::Io(_)` meant that the function  had to immediately return ( as in 
[word_count_from_reader_specialized()](https://github.com/uutils/coreutils/blob/6e09cbaefdb5094bf8c47fd52c40649390267186/src/uu/wc/src/wc.rs#L626C17-L626C36
)), the other Err i.e., `BufReadDecoderError::InvalidByteSequence(bytes)` did not require an early return (as in [update the 'total.bytes' variable ](https://github.com/uutils/coreutils/blob/6e09cbaefdb5094bf8c47fd52c40649390267186/src/uu/wc/src/wc.rs#L621)).

Hence, I could not fully follow your proposed solution. I will try to figure something else out unless you think the current fix is good enough. Please lmk. Thanks!

**Comment by sylvestre** [comment]
feels free to propose a different way to decrease the cognitive complexity :)
it was just a clue

**Comment by harshRn** [comment]
@sylvestre Done with the refactoring, I believe. Quick question : Do you think that abstracting out information about the line currently being processed in a file could be a good idea , or just an unnecessary addition ?
I am pointing towards the variables `current_len` (tracks the length of the line which helps in case the line is broken up because of chunking) and `in_word` (similar but tracking if the processing breaks up a word in parts due to chunking).
Appreciate your insight and time !!
