### ISSUE TITLE
FreeBSD: fstype `zfs` is known to uutils `df -T` but not `stat -f`

### ISSUE THREAD

**Issue by cre4ture** [uutils/coreutils#6067]
On FreeBSD, the filesystem type `zfs` is known to uutils `df -T` but not `stat -f`

```shell
uli@vm-free-bsd-uli:~/rust/coreutils $ target/debug/coreutils stat -f .
  File: "."
    ID: 0        Namelen: 255     Type: UNKNOWN (0xde)
Block size: 131072     Fundamental block size: 512
Blocks: Total: 67362136   Free: 58702200   Available: 58702200
Inodes: Total: 58800526   Free: 58702200
uli@vm-free-bsd-uli:~/rust/coreutils $ 
```
```
uli@vm-free-bsd-uli:~/rust/coreutils $ target/debug/coreutils df -PTh .
Filesystem     Type Size  Used Avail Use% Mounted on
zroot/usr/home zfs   33G  4.2G   28G  13% /usr/home
uli@vm-free-bsd-uli:~/rust/coreutils $ 
```

**Comment by hanbings** [comment]
Hello, 
I added a match for `0xDE` to FreeBSD's `zfs` at https://github.com/uutils/coreutils/blob/main/src/uucore/src/lib/features/fsext.rs#L882 File system support.
This change makes the `stat` command work properly, but I feel like this might not be the best solution.

Because I also read the relevant code of `df`, it also uses `MountInfo` to obtain file system information like `stat`. However, the results of `stat` and `df` are inconsistent, which seems unreasonable.

Maybe I should look for another solution?
