### ISSUE TITLE
Can GNU-specific behavior be turned off at build time?

### ISSUE THREAD

**Issue by xplshn** [uutils/coreutils#6646]
Hi, I was wondering if uutils/coreutils could become compliant (Not compile flags/functionality/behavior that isn't POSIX). Is that possible?

**Comment by just-an-engineer** [comment]
Maybe tool to tool, but not specifically. I know the project aims to be drop-in, so any GNU functionality should be almost exactly replicated, and where it's not, it's considered a bug. But that doesn't mean the tools can't go above and beyond. But it can also be a hindrance, ik our `seq` is more accurate due to the data type/structure we use to store everything, but GNU uses a `long double`, which gives it great precision, but not as accurate as the one here.
You can see it in this in #6244 and #5759, and @BenWiederhake comments on the line some tools are starting to walk between accuracy/correctness, and compatibility.
With that said, if you had a specific tool in mind you wanted to make more accurate, you can always code that up, add a command line flag for non-GNU compatible stuff, and make a PR. But tl;dr: I don't think there's much that isn't GNU compliant that can be turned off. But I don't know all the tools, either

**Comment by xplshn** [comment]
Ah, thanks for all the info. I'm actually very much against GNU, the license, and the bloat, I was looking for `busybox` alternatives, and uutils is MIT licensed, so it caught my attention.

**Comment by just-an-engineer** [comment]
Glad to hear. I agree with a lot of that. Feel free to contribute some code, we'd love to have the help!
