### ISSUE TITLE
pre-commit: assumes specific rust version

### ISSUE THREAD

**Issue by BenWiederhake** [uutils/coreutils#6730]
I use the rust 1.70.0 toolchain by default, to prevent myself from accidentally using features that would break our MSRV. For a long time, our pre-commit script worked, because it explicitly invoked `+nightly`. This was changed in #6715 for a good reason, but now this runs clippy 1.70.0, which doesn't understand all the new-fangled clippy-options:

```
error: error reading Clippy's configuration file `/home/user/workspace/coreutils-rs/.clippy.toml`: unknown field `check-private-items`, expected one of <SNIP very long list>
```

Suggestion: In the pre-commit hook, invoke `cargo +stable clippy …`. What do you think?

Workaround: `rustup run stable git commit …`

CC @dcampbell24

**Comment by dcampbell24** [comment]
You can choose that specific version like `cargo +1.70.0 clippy` and I see that it fails with the above error. It seems that our MSRV is wrong. The first version that doesn't fail is 1.76, but it gives some warnings about us listing not yet existing `allow`s.

**Comment by BenWiederhake** [comment]
> change out MSRV to 1.76

That's probably going to meet a lot of resistance or be impossible, given that the maintainers already refuse to upgrade to 1.74 (useful for OsStr to byte conversions).

I think changing the pre-commit hook should be enough.

Alternatively, if that is even possible: Use `build.rs` to emit the necessary clippy-configs dynamically in response to the currently active Rust version, somehow.

**Comment by dcampbell24** [comment]
So change to `cargo +1.70 clippy` and `cargo +1.70 fmt` and fix the errors (by removing the not yet existing features).

**Comment by dcampbell24** [comment]
I am wondering about how to handle warnings, because they don't stop compilation. You could  just remove all the causes of failure on the `1.70` version of rust, but it feels like you should optimize for the version you say you are supporting. You can always run `cargo clippy` or `cargo fmt` to get the newest features, but you can't enable those features if it would make `1.70` not compile. And maybe you shouldn't enable anything that causes a warning for version `1.70`, but I am uncertain where the warnings should lie.

**Comment by BenWiederhake** [comment]
Again, I'm suggesting `cargo +stable clippy`.

**Comment by dcampbell24** [comment]
We should make sure that `1.70` at least compiles since we are claiming to support it. Otherwise, I guess it is okay to optimize for the latest version of Rust (when I run `cargo +stable clippy version` I get 1.81).

**Comment by dcampbell24** [comment]
So... we should change `.clippy.toml` to `msrv = "1.78.0"` because that is what it actually is.

**Comment by tertsdiepraam** [comment]
Does clippy.toml not follow `rust-version` in `Cargo.toml`? If anything should be the source of truth on MSRV then it should be that field.

I'm a bit confused about the discusssion here. The MSRV seems to be fine at the moment. It _compiles_ without warnings. Clippy is not part of the MSRV. It also should not impact the field of MSRV for Clippy, because that's not about the minimum Clippy version but the minimum Rust version.

It should always be fine to run clippy with a higher version as long as the msrv field is set appropriately. So I agree with @BenWiederhake that `+stable` is the solution here.

> given that the maintainers already refuse to upgrade to 1.74 (useful for OsStr to byte conversions).

I'm not involved much anymore due to time constraints, but I'm always with upgrading if it really helps us cut dependencies and clean up the code. Let's discuss that in another issue.

**Comment by dcampbell24** [comment]
It seems that it doesn't. Actually I have no idea what that field does other than act as a sign post of what version you should be using. Correct me if I am wrong.

clippy is packaged with the version of rust. Try running `cargo +1.77 clippy --workspace --all-targets --all-features` and you will see that it errors out, but `cargo +1.78 clippy --workspace --all-targets --all-features` is ok (with warnings).

**Comment by tertsdiepraam** [comment]
There's two concepts so separate here: the versions for which the code will run and which version of clippy we're using.

Clippy's msrv and Cargo.toml's rust-version are both about the former. For example, it stops clippy from suggesting methods that aren't available in your minimum Rust version. It is essentially a signpost for _users_ not for developers. Hence the current version is fine, because the code compiles and therefore it's our MSRV.

I did check and clippy indeed doesn't seem to read rust-version, so we should keep both.

rust-version is currently mostly just a field (except that some tools read it), but it will be really important with the MSRV-aware resolver that's currently being added to cargo.

**Comment by dcampbell24** [comment]
I was wrong about the field `msrv` being mostly useless [1]. It seems that if you don't specify `msrv` then `rust-version` is checked, so we can probably get rid of `msrv`. Also, we can omit the patch version, so `1.70` instead of `1.70.0`.

[1]: https://github.com/rust-lang/rust-clippy?tab=readme-ov-file#specifying-the-minimum-supported-rust-version
