### ISSUE TITLE
Implement date

### ISSUE THREAD

**Issue by dylanscode** [uutils/coreutils#811]
I got this

**Comment by Anachron** [comment]
When?

**Comment by dylanscode** [comment]
Sorry for the lack of communication, that's never excusable.

The program is mostly done, the issue is finding a way to set the system date using pure Rust. I'd be happy to push what I have so far, but my impression is that you'd rather wait until I have fully working version.

**Comment by tshepang** [comment]
I would rather we have an incomplete version. Also, a bunch of the other tools are also incomplete (last I checked).

**Comment by LegNeato** [comment]
@dylanscode: Please put up a PR. If you don't have time to take it all the way I am willing to build on what you have. For setting the date, I think https://github.com/rust-lang/libc/pull/473 should help.

**Comment by adeschamps** [comment]
I made a partial implementation (PR #1029 ). Some of the main things that don't work yet are:
- Parsing the variety of ways to represent a date ("tomorrow", "next year", etc.)
- Setting the system clock
- Printing the current time zone (although that work needs to be done on the `chrono` crate - it should be pretty simple on this end)

It could also use some unit tests. I wasn't sure how to approach that, because the output of `date` can be different every time you run it.

**Comment by evanjs** [comment]
Interested in `date -d` and such in Rust, but from the little I've seen the gnulib code is sort of scary and wasn't sure if anybody has made any progress on this.

**Comment by sylvestre** [comment]
It has been implemented now
https://github.com/uutils/coreutils/pull/1491
