### ISSUE TITLE
Implement `tail --retry <FILE>` to keep trying to open the file <FILE>

### ISSUE THREAD

**Issue by fitzgen** [uutils/coreutils#847]
From `tail`'s man page:

```
       --retry
              keep trying to open a file if it is inaccessible
```

**Comment by mrmiywj** [comment]
Hi, I will pick this up.

**Comment by GaurangTandon** [comment]
Hi. I have done almost half of the code in direction of this issue. Here is the commit: https://github.com/GaurangTandon/coreutils/commit/6d165b05d23d5def0c7537f2be3a7afb96dc35a9. Some [quick read on `tail`](https://unix.stackexchange.com/questions/291932/).

I am now at the critical juncture of deciding how to actually implement this functionality. I asked the question: [Watch for file deletion and recreation](https://stackoverflow.com/q/65613880/) and got an answer along two lines:

1. counting links on an open file object 
2. using `notify` crate

I find it impossible to use the first method, because, as soon a `BufReader` is created for a File object, ([line link](https://github.com/GaurangTandon/coreutils/commit/6d165b05d23d5def0c7537f2be3a7afb96dc35a9#diff-4c2d7c4602c9d8624bf4fa7690c08b715958522b11037ac490b00c2eb194d22dR245)), the actual `file` object is moved and no longer usable. I do not see a way out of this.

I wish to ask if the team has any reservations on using the external `notify` crate, or if they have any other suggestion on how to implement this.

Thank you.

**Comment by sylvestre** [comment]
I clearly prefer to rely on existing crates instead of reinventing the wheel.
The main constraints is that we have a requirement on Rust 1.32

**Comment by sylvestre** [comment]
Don't hesitate to submit a PR (even if this isn't ready, just use the draft mode)

**Comment by GaurangTandon** [comment]
> I clearly prefer to rely on existing crates instead of reinventing the wheel.
> The main constraints is that we have a requirement on Rust 1.32

Alright, I'll try to see what can be done in the existing code itself, and update the PR in a day.
