### ISSUE TITLE
tr is broken when making on 'commit 2ab055445b410f197178fa5ce705ea7911bc0c5c'

### ISSUE THREAD

**Issue by junjiemars** [uutils/coreutils#865]
```
src/tr/tr.rs:86:41: 86:57 error: mismatched types:
 expected `usize`,
    found `&usize`
(expected usize,
    found &-ptr) [E0308]
src/tr/tr.rs:86                 let trc = match map.get(&(char as usize)) {
                                                        ^~~~~~~~~~~~~~~~
src/tr/tr.rs:86:41: 86:57 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `tr`.
```

I tried 2 boxes one Ubuntu 14.04 64-bits another is OSX 10.11, the result is same.

**Comment by ebfe** [comment]
Which rust version? Can't reproduce on master with rust 1.7 or 1.8.

**Comment by junjiemars** [comment]
Hi, @ebfe , the version is 1.7

**Comment by knight42** [comment]
Same problem here.
```
$ rustc -V
rustc 1.10.0-dev (5158f3b28 2016-05-06)
```

**Comment by jbcrail** [comment]
The root of the problem is the `vec_map` library used by `tr`. In `vec_map` 0.4, the `get` method accepted `&usize`. For 0.5 and later, `get` switched to `usize`.

Depending on whether coreutils is built using `make` or `cargo build`, different versions of `vec_map` will be downloaded since `src/tr/Cargo.toml` doesn't pin `vec_map` to a certain version.

If we pin to the latest version and change `&usize` to `usize`, this will fix this issue.
