### ISSUE TITLE
No "pinky" command under OS X 10.11

### ISSUE THREAD

**Issue by dmilith** [uutils/coreutils#966]
Shot with failed test: http://ół.pl/e8213645432a3d118c2264ff60692d64.png

**Comment by knight42** [comment]
@dmilith Thanks for your report.
Actually people indeed cannot find `pinky` on  OS X since GNU coreutils is not installed by default.

However,  whether `pinky` is absent or not doesn't matter, because `pinky` obtains  desired info by calling some C functions. I guess the problem is caused by the difference  between your OS's environment and travis CI's and this test may be ignored.

Anyway, as your snapshot didn't cover the complete error message, could you paste it here? I want to see what info `pinky` should print on your host.

**Comment by dmilith** [comment]
There're simply no such command in base system in OSX 10.11. So it's more about skipping test of "pinky" under OSX :)

**Comment by knight42** [comment]
ok, will do
